In [ ]:
# Python supports Dynamic Typing or Dynamic Programming which means Python by default can understand
# which is a String,Integer,Float etc...

In [1]:
print("This is Python Programming")

This is Python Programming


In [2]:
a,b,c = 10,"shashank",'Hello'

In [3]:
a

10

In [4]:
b

'shashank'

In [5]:
c

'Hello'

In [8]:
testt = a,b,c

In [7]:
print(a,b,c)

10 shashank Hello


In [9]:
type(testt)

tuple

In [10]:
True + True + True + False + True

4

In [11]:
False - True + True

0

In [12]:
1+1

2

In [13]:
True / False

ZeroDivisionError: division by zero

In [14]:
n = 46 + 6j # This is a complex number, complex number = Real Number + Imaginary number
            # Imaginary number can only be denoted by 'j' not any other alphabet or character

In [15]:
n

(46+6j)

In [16]:
type(n)

complex

In [17]:
n.real

46.0

In [18]:
n.imag

6.0

In [19]:
m = 34 + 4j

In [21]:
p = n + m # adding complex numbers

In [22]:
p

(80+10j)

In [23]:
p.real

80.0

In [24]:
p.imag

10.0

In [25]:
1 + 'Shashank'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [26]:
d = 'sha'+'sha'

In [27]:
d

'shasha'

In [29]:
s = str(1)+'shashank'

In [30]:
s

'1shashank'

In [31]:
type(s)

str

In [32]:
e = "1"+"shashank" # This is Strong Typing where in we are representing integer as a string by including it between 
                   # the quotes

In [33]:
e

'1shashank'

In [39]:
# Conctination Operation (adding strings)
d = 'sha'+'sha'+'sha'
e = "1"+"shashank"
f = 'sha' *3
print(d)
print(e)
print(f)

shashasha
1shashank
shashasha


In [35]:
z = 1 + 1.1

In [36]:
z # The addition of integer and float output is being converted to a Float, This is called Upcasting

2.1

In [40]:
a = input() # here we are taking input manually or through the console from the user

12


In [41]:
a

'12'

In [42]:
b = input("Enter an integer: ")

Enter an integer: 12


In [43]:
b

'12'

In [44]:
type(b) # Even though we have given an integer we get type as str in input()

str

In [77]:
# This way whatever the value we enter gets converted to an integer not a string
a = int(input("Enter value of a: "))
b = int(input("Enter value of b: "))
c = int(input("Enter value of c: "))

Enter value of a: 12
Enter value of b: 10
Enter value of c: 6


In [85]:
a,b,c

(12, 10, 6)

In [78]:
d = (a+b)/c

In [79]:
d

3.6666666666666665

In [80]:
e = 10 + 4j

In [81]:
f = d + e

In [82]:
f

(13.666666666666666+4j)

In [86]:
type(f)

complex

In [83]:
g = str(f) + "shashank" #converting to string is called TypeCasting, that is changing its type to a string

In [84]:
g

'(13.666666666666666+4j)shashank'

# Conditional Statements

In [91]:
a = int(input("Enter a number less than 34: "))
if a<34:
    pass

Enter a number less than 34: 32


In [93]:
a = int(input("Enter a number less than 34: "))
if a<34:
    print("Number is less than 34")

Enter a number less than 34: 35


In [94]:
a = int(input("Enter a number less than 34: "))
if a<34:
    print("Number is less than 34")

Enter a number less than 34: 32
Number is less than 34


In [113]:
salary = int(input("Enter your Salary: "))

if salary >= 10000:
    pass
    if salary < 15000:
        print("Buy a used Car")
    elif salary > 15000:
        print("Buy a new Car")
    else:
        print("Dont buy a car")
elif salary >= 5000:
    print("Buy a bike")
else:
    print("Start Saving")

Enter your Salary: 4990
Start Saving


In [129]:
a = 10
b = 20

a == 10 and b == 20

True

In [125]:
# AND Condition
review = int(input("Enter the movie Review between 0-10: "))

if review <= 1:
    print("POOR")
elif review > 1 and review <= 3:
    print('BAD')
elif review > 3 and review <=6:
    print('AVERAGE')
elif review >6 and review <= 8:
    print('GOOD')
elif review > 8 and review <=10:
    print('VERY GOOD')
else:
    pass

Enter the movie Review between 0-10: 0
POOR


In [133]:
a = 10
b = 20

a == 10 or b == 21

True

In [152]:
# using OR Condition
movie = input('Enter movie review as good or bad: ')
theater_condition = input('Enter theater condition as good or bad: ')

if movie == 'good' and theater_condition == 'good':
    print('Definitely Will go watch a movie')
elif movie == 'bad' and theater_condition == 'bad':
    print('Definitely will not go watch a movie')
elif movie == 'bad' or theater_condition == 'good':
    print('Will not go watch a movie')
elif movie == 'good' or theater_condition == 'bad':
    print('Might go watch a movie')
else:
    print('Type good or bad and nothing else')

Enter movie review as good or bad: good
Enter theater condition as good or bad: bad
Might go watch a movie


# While loop

In [153]:
initial_speed = 0
final_speed = 15

while initial_speed < final_speed:
    initial_speed = initial_speed + 1
    print(initial_speed)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [156]:
# using Break statement
initial_speed = 0
final_speed = 15
count = 0

while initial_speed < final_speed: #here this is true for infinity
    print('This is speed')
    count = count + 1
    if count == 10:
        break

This is speed
This is speed
This is speed
This is speed
This is speed
This is speed
This is speed
This is speed
This is speed
This is speed


In [4]:
# While-else, here else statement works only after while statement is false
i = 0 
j = 10
k= 1
while i < j:
    print(i)
    i = i+1
else:
    while k< j:
        print(k)
        k = k+1
        print('This is nested While statement condition')
    print('This is While-Else Statement')

0
1
2
3
4
5
6
7
8
9
1
This is nested While statement condition
2
This is nested While statement condition
3
This is nested While statement condition
4
This is nested While statement condition
5
This is nested While statement condition
6
This is nested While statement condition
7
This is nested While statement condition
8
This is nested While statement condition
9
This is nested While statement condition
This is While-Else Statement


In [540]:
i = 0
j = 10
count = 0
while i < j:
    count = count + i
    i = i+1
    print('count is {},i is {}'.format(count,i))
print('The total count is : {}'.format(count))

count is 0,i is 1
count is 1,i is 2
count is 3,i is 3
count is 6,i is 4
count is 10,i is 5
count is 15,i is 6
count is 21,i is 7
count is 28,i is 8
count is 36,i is 9
count is 45,i is 10
The total count is : 45


# For loop

In [42]:
name = "my name is shashank"

for i in name:
    print(i)

m
y
 
n
a
m
e
 
i
s
 
s
h
a
s
h
a
n
k


In [44]:
name = "my name is shashank"

for i in name:
    print(i)
else: # this is executed only if the for loop is exhausted
    for i in name:# this is nested for loop
        if i == 's':
            print(i)
    print('This is For-Else')

m
y
 
n
a
m
e
 
i
s
 
s
h
a
s
h
a
n
k
s
s
s
This is For-Else


In [51]:
# Using BREAK command
name = "my name is shashank"

for i in name:
    if i == 'n':
        break # here loop is broken so 'else' statement will not be executed
    print(i)
else: # this is executed only if the for loop is exhausted
    for i in name:# this is nested for loop
        if i == 's':
            print(i)
    print('This is For-Else')

m
y
 


In [54]:
# Using Continue command
name = "my name is shashank"

for i in name:
    if i == 'n':
        continue  # here continue command is used and the loop gets exhausted
    print(i)
else: # this is executed only if the for loop is exhausted
    for i in name:# this is nested for loop
        if i == 's':
            print(i)
    print('This is For-Else')

m
y
 
a
m
e
 
i
s
 
s
h
a
s
h
a
k
s
s
s
This is For-Else


In [1105]:
a = int(input("Enter a number: "))
lst = [1,2,3,4,4,5,4,6,7,8,9,10,11]
choosen_num = []

for i in lst:
    if i == a:
        choosen_num.append(i)
print(choosen_num)

Enter a number: 6
[6]


In [56]:
name = 'ineuron'
not_n = ''

for i in range(len(name)):
    if name[i] == 'n':
        continue
    else:
        not_n = not_n + name[i]
print(not_n)

ieuro


In [1120]:
#Task
n = int(input('Enter how many fibonacci numbers you want: '))
a = 1
b = 0
for i in range(n):
    c = a+b
    b = a
    a = c
    print(c)

Enter how many fibonacci numbers you want: 10
1
2
3
5
8
13
21
34
55
89


In [74]:
plus = 7

for i in range(0,plus):
    for j in range(0,i+1):
        print('+',end='')
    print('\r')
#  "\t" is a tab, "\n" is a newline, and "\r" is a carriage return        

+
++
+++
++++
+++++
++++++
+++++++


In [342]:
#Task
n=int(input('Enter number of rows: '))
for i in range(n,0,-1):
    for j in range(n-i):
        print(' ',end='')
    for j in range(2*i-1):
        print('*',end='')
    print('\t')

Enter number of rows: 9
*****************	
 ***************	
  *************	
   ***********	
    *********	
     *******	
      *****	
       ***	
        *	


In [341]:
#Task
n=int(input('Enter number of rows: '))
m = 0
for i in range(n,-1,-1):
    for j in range(0,m):
        print(' ',end='')
    m = m+1
    for j in range(i):
        print('*',end=' ')
    print('\r')

Enter number of rows: 8
* * * * * * * * 
 * * * * * * * 
  * * * * * * 
   * * * * * 
    * * * * 
     * * * 
      * * 
       * 
        


In [391]:
#Task
n=int(input('Enter number of rows: '))
m = n-1
for i in range(0,n):
    for j in range(0,m):
        print(' ',end='')
    m = m-1
    for j in range(i+1):
        print('*',end=' ')
    print('\r')

Enter number of rows: 5
    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [191]:
#Task
n = 5
m = 0
while m<n:
    if m == 0:
        print('++++',end='')
        print('*',end='')
        m = m+1
    elif m == 1:
        print('+++',end='')
        print('***',end='')
        m = m+1
    elif m == 2:
        print('++',end='')
        print('*****',end='')
        m = m+1 
    elif m == 3:
        print('+',end='')
        print('*******',end='')
        m = m+1
    elif m == 4:
        print('',end='')
        print('*********',end='')
        m = m+1
    else:
        print('Max limit reached')
        m = m+1
    print('\r')

++++*
+++***
++*****
+*******
*********


In [344]:
#Task
n = int(input('Enter number of rows: '))
m = 0
p = n
while m<n:
    print(' '*(p-1)+'* '*(m+1))
    p= p-1
    m = m+1

Enter number of rows: 5
    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [339]:
#Task
user_input = int(input('Enter number of rows'))
row = 0

while user_input > row:
    row = row + 1
    spaces = user_input - row # this gives number of spaces
    space_counter = 0
    while space_counter < spaces:
        print(' ',end='')
        space_counter = space_counter + 1
    num_stars = (2 * row) -1 # this only gives odd numbers in sequence(this gives number of stars)
    while num_stars > 0 :
        print('*',end='')
        num_stars = num_stars - 1
    print('\r')

Enter number of rows12
           *
          ***
         *****
        *******
       *********
      ***********
     *************
    ***************
   *****************
  *******************
 *********************
***********************


### About \r
'\r' means 'carriage return' and it is similar to '\n' which means 'line break' or more commonly 'new line'

in the old days of typewriters, you would have to move the carriage that writes back to the start of the line, and move the line down in order to write onto the next line.

in the modern computer era we still have this functionality for multiple reasons. but mostly we use only '\n' and automatically assume that we want to start writing from the start of the line, since it would not make much sense otherwise.

however, there are some times when we want to use JUST the '\r' and that would be if i want to write something to an output, and the instead of going down to a new line and writing something else, i want to write something over what i already wrote, this is how many programs in linux or in windows command line are able to have 'progress' information that changes on the same line.

nowadays most systems use only the '\n' to denote a newline. but some systems use both together.

you can see examples of this given in some of the other answers, but the most common are:

windows ends lines with '\r\n'
mac ends lines with '\r'
unix/linux use '\n'
and some other programs also have specific uses for them.

In [71]:
carriage_return = "I will use a carriage\rreturn"
carriage_use = 'this is the use of \rcarriage return'
print (carriage_return)
print(carriage_use)

return
carriage return


In [442]:
new_line = "I will use a carriage\nreturn"
print(new_line)

I will use a carriage
return


# String Parsing and Indexing

In [903]:
name = 'my name is shashank'
namehyphen = 'my-name-is-shashank'
email = 'shashank@gmail.com'
email2 = 'shashank@bhojappa@gmail.com'
my_name = 'shashank'
my_name_upper = 'SHASHANK'
my_name_S = 'Shashank'
space = '  shashank  '


In [908]:
# Built in functions
print(name.upper())
print(name.lower())
print(my_name_S.swapcase()) # if the string is lower case it will make it uppercase and if it is lower it will make it upper
print(name.split())
print('.'.join(name))
print(space.strip())# strips space on both left and right side
print(space.rstrip())# removes spaces on right side
print(space.lstrip())# removes spaces on left side
print(name.replace('shashank','bhojappa')) # replaces shashank with bhojappa
print(namehyphen.split('-')) #here the separator is not retained
print(email.partition('@')) # here the separator element is also retained
print(email2.partition('@')) # here it will encounter only first occurence, 2nd occurence is neglected
print(type(email.partition('@')))
print(name.find('a')) # find index of 'a', only first occurence
print(name.find('z')) # -1 means, that string is not available
print(my_name.center(20,'z'))# here the total length will be 20, 
                             #whatever the rest is occupied by 'z' keepin my_name in center
# print(my_name.center(20,'za')) --> only single character can be passed, more than 1 character will give error
print(len(my_name.center(20,'z')))
print(namehyphen.isalnum()) # is function always gives bo0lean output
print(my_name.isalnum())
print(my_name.isupper())
print(my_name_upper.isupper())
print(my_name_S.isupper())
print(my_name_S.islower())
print(my_name_S.istitle())# title means first character is capital letter
print(my_name_S.endswith('k'))
print(my_name_S.endswith('r'))

MY NAME IS SHASHANK
my name is shashank
sHASHANK
['my', 'name', 'is', 'shashank']
m.y. .n.a.m.e. .i.s. .s.h.a.s.h.a.n.k
shashank
  shashank
shashank  
my name is bhojappa
['my', 'name', 'is', 'shashank']
('shashank', '@', 'gmail.com')
('shashank', '@', 'bhojappa@gmail.com')
<class 'tuple'>
4
-1
zzzzzzshashankzzzzzz
20
False
True
False
True
False
False
True
True
False


In [928]:
sent = 'We all are a part of Full Stack'

#Make everythin lower
print(sent.lower())
# find how many time 'a' has occured
print('Number of times a has occured: ',sent.count('a'))

# make a list of all the index where 'a' has occured
#1st way
y = [i for i in range(len(sent)) if sent[i] == 'a']
print(y)

#2nd way
a_index = []
for i in range(len(sent)):
    if sent[i] == 'a':
        a_index.append(i)
print(a_index)

#replace all 'a' with iNeuron
iNeuron = sent.replace('a','iNeuron')
print(iNeuron)

#Print all words as a list
print(sent.split())


we all are a part of full stack
Number of times a has occured:  5
[3, 7, 11, 14, 28]
[3, 7, 11, 14, 28]
We iNeuronll iNeuronre iNeuron piNeuronrt of Full StiNeuronck
['We', 'all', 'are', 'a', 'part', 'of', 'Full', 'Stack']


### Placeholder

In [576]:
def greeting(name):
    return "Hello {} Welcome to python.".format(name)

In [577]:
greeting('Shashank')

'Hello Shashank Welcome to python.'

In [578]:
def welcome_email(first_name,last_name):
    return "Your Firstname is {}, and your Lastname is {}".format(first_name,last_name)

In [579]:
welcome_email('James','Bond')

'Your Firstname is James, and your Lastname is Bond'

In [580]:
def welcome_email(first_name,last_name,age):
    return "Your Firstname is {firstname}, and your Lastname is {lastname},Aged {age} years".format(
        firstname=first_name,lastname=last_name,age=age)

In [581]:
welcome_email('Bruce','Wayne',45)

'Your Firstname is Bruce, and your Lastname is Wayne,Aged 45 years'

In [427]:
def welcome_email(first_name,last_name,age):
    return "Your Firstname is {0}, and your Lastname is {1},Aged {2} years and Firstname is {0}".format(
        first_name,last_name,age,first_name)

In [428]:
welcome_email('Bruce','Wayne',45)# here we have resued first_name twice even though in parameters 
# first_name is mentioned only once

'Your Firstname is Bruce, and your Lastname is Wayne,Aged 45 years and Firstname is Bruce'

In [593]:
first_name = input('What is your First name? ')
last_name = input('What is your Last name? ')
print('My name is {} {}'.format(first_name,last_name))

What is your First name? Shashank
What is your Last name? Bhojappa
My name is Shashank Bhojappa


### Indexing

In [13]:
name[1]

'y'

In [14]:
name[:]

'my name is shashank'

In [16]:
name[3:9]

'name i'

In [17]:
name[3:]

'name is shashank'

In [18]:
name[:11]

'my name is '

In [19]:
name[-1]

'k'

In [23]:
name[-5:]

'shank'

In [24]:
name[-5:-2]

'sha'

In [40]:
name[3:-8]

'name is '

In [32]:
name[2:18:2] # here the[2(start point):18(end point):2(step size)]

' aei hsa'

In [33]:
name[2::2]

' aei hsak'

In [35]:
name[18:2:-1] # this will give us in reverse order

'knahsahs si eman'

In [36]:
name[18::-1]

'knahsahs si eman ym'

In [37]:
name[18:2:-2]

'kash iea'

In [38]:
name[::-1]

'knahsahs si eman ym'

In [876]:
name = 'my name is shashank' 

for i in range(len(name)):
    print(name[i])

m
y
 
n
a
m
e
 
i
s
 
s
h
a
s
h
a
n
k


In [929]:
name = 'my name is shashank' #print string values in reverse order

for i in range(1,len(name)):
    print(name[-i])

k
n
a
h
s
a
h
s
 
s
i
 
e
m
a
n
 
y


In [939]:
name = 'my name is shashank' #print string values in reverse order using while loop
name_len = len(name)-1
while name_len >= 0:
    print(name[name_len])
    name_len = name_len - 1

k
n
a
h
s
a
h
s
 
s
i
 
e
m
a
n
 
y
m


In [ ]:
name = 'my name is shashank'

In [897]:
a = name.find('name') # find all the indexes of the word'name'

for i in range(len('name')):
    print(a + i)

3
4
5
6


In [942]:
#Task
# Find Vowels in a string
name = 'INeuron' 
vowels = 'aAeEiIoOuU'

for i in name:
    if i in vowels:
        print(i,'is a vowel')
    else:
        print(i,'is not a vowel')

I is a vowel
N is not a vowel
e is a vowel
u is a vowel
r is not a vowel
o is a vowel
n is not a vowel


In [945]:
#Task
# check for palindrome
name = input('Enter a name to check if its a Palindrome: ')

if name[::-1] == name:
    print('{} is a palindrome'.format(name))
else:
    print('{} is not a palindrome'.format(name))

Enter a name to check if its a Palindrome: nitin
nitin is a palindrome


## List

Lists
A list is a data structure in Python that is a mutable, or changeable, ordered sequence of elements. Each element or value that is inside of a list is called an item. Just as strings are defined as characters between quotes, lists are defined by having values between square brackets [ ]

**List is mutable, changable and it can contain any elements inside, it can be of any data type strings or integers

In [428]:
type([])

list

In [429]:
lst_example=[]

In [430]:
type(lst_example)

list

In [1048]:
# Giving list as input
l = []

for i in range(5):
    l.append(int(input('Enter 5 values: ')))
print(l)

Enter 5 values: 1
Enter 5 values: 2
Enter 5 values: 3
Enter 5 values: 4
Enter 5 values: 5
[1, 2, 3, 4, 5]


In [946]:
name = 'shashank'
list(name)

['s', 'h', 'a', 's', 'h', 'a', 'n', 'k']

In [947]:
name = ['shashank']
name

['shashank']

In [431]:
lst=list() # another way of initializing list

In [432]:
type(lst)

list

In [630]:
n = [1,5,43,3,21,98,321,15,5]

In [631]:
n.sort()

In [632]:
n

[1, 3, 5, 5, 15, 21, 43, 98, 321]

In [633]:
n.sort(reverse=True)

In [634]:
n

[321, 98, 43, 21, 15, 5, 5, 3, 1]

In [643]:
a = [1,2,3,4,5]
b = [10,11,12]
c = [21,34,56,78,12,45,3]

d = [a,b,c]
d

[[1, 2, 3, 4, 5], [10, 11, 12], [21, 34, 56, 78, 12, 45, 3]]

In [644]:
d[2][::2]

[21, 56, 12, 3]

In [645]:
d[::-1] # reverse list order

[[21, 34, 56, 78, 12, 45, 3], [10, 11, 12], [1, 2, 3, 4, 5]]

In [646]:
m = []
e = d[::-1]

for i in e:
    m.append(i[::-1])
print(m)
# here not only the list , but also the values inside each list is reversed

[[3, 45, 12, 78, 56, 34, 21], [12, 11, 10], [5, 4, 3, 2, 1]]


In [648]:
m

[[3, 45, 12, 78, 56, 34, 21], [12, 11, 10], [5, 4, 3, 2, 1]]

In [650]:
o = []
for i in m:
    o.append(i[2]*2)
print(o)
# extract 2 index values from every list and multiply it by 2

[24, 20, 6]


# List Comprehension

In [651]:
o = []

[o.append(i[2]*2) for i in m] # using list comprehension
print(o)

[24, 20, 6]


In [1086]:
li = []

for i in range(10):
    if i%2 == 0:
        li.append('even')
    else:
        li.append('odd')
print(li)

['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']


In [1085]:
# usng list comprehension
# condition is written on the left side for print condtion

['even' if i%2 == 0 else 'odd' for i in range(10)]

['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']

In [1091]:
li = [1,2,3,4]

['two' if i==2 else 'not two' for i in li ]

['not two', 'two', 'not two', 'not two']

In [1103]:
l = []
for i in range(10):
    if i ==2:
        l.append('two')
    elif i==3:
        l.append('three')
    else:
        l.append('test')
print(l)

['test', 'test', 'two', 'three', 'test', 'test', 'test', 'test', 'test', 'test']


In [1102]:
['two' if i==2 else 'three' if i==3 else 'test' for i in range(10)] # elif condition

['test',
 'test',
 'two',
 'three',
 'test',
 'test',
 'test',
 'test',
 'test',
 'test']

In [1092]:
#creating nested lists using for loop
mat = []

for i in range(3):# we are creating 3 nested lists
    mat.append([])#add empty list
    for j in range(5): #creating 4 values inside the nested list
        mat[i].append(j)
print(mat)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [1094]:
#creating nested lists using list comprehension
[[j for j in range(5)] for i in range(3)]

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

In [1099]:
l = []
for i in range(10):
    if i%2==0:
        if i%3==0:
            l.append(i)
print(l)

[0, 6]


In [1095]:
[i for i in range(10) if i%2==0 if i%3==0]# multiple if condition

[0, 6]

In [871]:
p = [3,4,5,4,6,7,6,[4,6,4,7,8],[4,3]] # remove all the 4 from list and nested list

for i in p:
    if i == 4:
        p.remove(i)
    if type(i) == list:
        for j in i:
            if j == 4:
                i.remove(j)
print(p)

[3, 5, 6, 7, 6, [6, 7, 8], [3]]


In [612]:
lst=['Mathematics', 'chemistry', 100, 200, 300, 204]

In [613]:
lst[::-1]

[204, 300, 200, 100, 'chemistry', 'Mathematics']

In [614]:
lst

['Mathematics', 'chemistry', 100, 200, 300, 204]

In [610]:
lst.reverse() # this makes changes permanent

In [611]:
lst

[204, 300, 200, 100, 'chemistry', 'Mathematics']

In [434]:
len(lst)

6

In [956]:
lis = [1,2,3,4,'happy',['egg','bird',7]]

print('happy' in lis)
print(3 in lis)
print(7 in lis)
print(7 in lis[5])
print('egg' in lis[5])

True
True
False
True
True


In [415]:
l1 = ['shashank',1234,34.6,True,45+6j,[4,5,6,'testing']]

In [418]:
for i in l1:
    print(type(i))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'complex'>
<class 'list'>


In [424]:
for i in l1:
    if type(i)== list:
        for j in i:
            print(type(j))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'str'>


In [427]:
for i in l1:
    if type(i) == list:
        n = 0
        for j in i:
            if type(j) == int:
                n = n+j
        print(n)
                

15


In [436]:
l1[5:1:-1]#Reverse order

[[4, 5, 6, 'testing'], (45+6j), True, 34.6]

In [437]:
l1[::-1]

[[4, 5, 6, 'testing'], (45+6j), True, 34.6, 1234, 'shashank']

In [439]:
list(range(4,20))

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [440]:
list(range(20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [443]:
list(range(4,10.1)) # Float object cannot be given,only integers should be given

TypeError: 'float' object cannot be interpreted as an integer

### Append - appends an object at the end of the list


In [552]:
[1,2,3,4] + ['shashank','guru']

[1, 2, 3, 4, 'shashank', 'guru']

In [735]:
l = [0,1,2,3,4]

In [736]:
l[0] = 'shashank' # we can replace values in list

In [737]:
l

['shashank', 1, 2, 3, 4]

In [608]:
a = [1,2,3,[4,5]]
b= ['shashank',3,6]

(a+b)*2

[1, 2, 3, [4, 5], 'shashank', 3, 6, 1, 2, 3, [4, 5], 'shashank', 3, 6]

In [446]:
lst=['Mathematics', 'chemistry', 100, 200, 300, 204]

In [447]:
lst.append("Krish")

In [448]:
lst.append(["John","Bala"])

In [449]:
lst

['Mathematics', 'chemistry', 100, 200, 300, 204, 'Krish', ['John', 'Bala']]

In [450]:
##Indexing in List
lst[6]

'Krish'

In [451]:
lst[7]

['John', 'Bala']

In [452]:
lst[:]

['Mathematics', 'chemistry', 100, 200, 300, 204, 'Krish', ['John', 'Bala']]

In [453]:
lst[1:]

['chemistry', 100, 200, 300, 204, 'Krish', ['John', 'Bala']]

In [454]:
lst[1:4]

['chemistry', 100, 200]

### Insert

In [455]:
## insert in a specific order

lst.insert(2,"Naik")

In [456]:
lst

['Mathematics',
 'chemistry',
 'Naik',
 100,
 200,
 300,
 204,
 'Krish',
 ['John', 'Bala']]

In [457]:
lst=[1,2,3]

In [458]:
lst.append([4,5])

In [459]:
lst

[1, 2, 3, [4, 5]]

In [502]:
l1 = [1,2,3,4,5]
l2 = []

for i in l1:
    l2.append(i+4)
print(l1)
print(l2)

[1, 2, 3, 4, 5]
[5, 6, 7, 8, 9]


In [525]:
l3 = [1,17,32,2,4,68,91,8,4,27]
l4 = []
l5 = [1,2,3,4,5,6,7]

In [505]:
for i in l3:
    if i>10:
        l4.append(i*i)
    else:
        l4.append(i*100)
print(l3)
print(l4)
        

[1, 17, 32, 2, 4, 68, 91, 8, 4, 27]
[100, 289, 1024, 200, 400, 4624, 8281, 800, 400, 729]


In [507]:
for i in l3:
    if len(l3)>=10:
        print('List is too long')
    else:
        l4.append(i*2)
print(l3)
print(l4)

List is too long
List is too long
List is too long
List is too long
List is too long
List is too long
List is too long
List is too long
List is too long
List is too long
[1, 17, 32, 2, 4, 68, 91, 8, 4, 27]
[]


In [513]:
for i in l5:
    if len(l5)>=10:
        print('List is too long')
    else:
        l4.append(i*2)
print(l5)
print(l4)

[1, 2, 3, 4, 5, 6, 7]
[2, 4, 6, 8, 10, 12, 14]


In [526]:
for i in range(len(l5)):
    print(i) # here i is not the list values, instead range of values from 0-6 (len(l5))
    if i < 5:
        l4.append(i+5)
    else:
        l4.append(i)
print(l4)
print(l5)

0
1
2
3
4
5
6
[5, 6, 7, 8, 9, 5, 6]
[1, 2, 3, 4, 5, 6, 7]


In [528]:
lst=['Mathematics', 'chemistry', 100, 200, 300, 204]
names = []

In [529]:
for i in lst:
    if type(i)==str:
        names.append(i)
print(names)

['Mathematics', 'chemistry']


### Extend

In [460]:
lst=[1,2,3,4,5,6]

In [461]:
lst.extend([8,9]) 
# when we are adding elelments in list it is just extending the elements inside the list , it is not nesting another list
# inside as it did here lst.append(["John","Bala"])

In [462]:
lst

[1, 2, 3, 4, 5, 6, 8, 9]

### Various Operations that we can perform in List


In [463]:
lst=[1,2,3,4,5]

In [464]:
sum(lst)

15

In [465]:
lst * 5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

### Pop() Method

In [467]:
lst.pop()

5

In [468]:
lst

[1, 2, 3, 4]

In [469]:
lst.pop(0)

1

In [470]:
lst

[2, 3, 4]

### count():Calculates total occurrence of given element of List


In [477]:
lst=[1,1,2,3,3,4,5]
lst.count(1)

2

In [478]:
lst.count(4)

1

In [479]:
lst.count(3)

2

In [480]:
#length:Calculates total length of List
len(lst)

7

In [483]:
# index(): Returns the index of first occurrence. Start and End index are not necessary parameters
lst.index(1,1,4) # start and stop index helps in finding the index of element between that start stop period

1

In [488]:
lst.index(4,1,6) # (value,start,stop)

5

In [489]:
##Min and Max
min(lst)

1

In [490]:
max(lst)

5

In [1081]:
# Task
#1. append another list
#2. insert list at index 1
#3. print index number of strings inside the nested lists
#4. remove the strings from inside the nested lists
#5. Extract 2nd element from all the nested lists


lists = [['sam',2,3,4,5],['sid','john',17,'van','guard',5,6,7],[32,67,89,34,12]]
#1
lists.append([14,56,'sunny',78,'oven'])
#2
lists.insert(1,['good','build','jaguar','pencil','aroma','ink','jack','kite',35,67,78,56+6j])
print('This is the old list: ',lists)

for i in lists:
    if type(i) == list:
        j = 0
        while j < len(i):
            if type(i[j]) == str:
                #3
                print('Index of {} is {} '.format(i[j],j))
            j = j+1
        j = 0
        while j < len(i):
            if type(i[j]) == str:
                #4
                i.remove(i[j])
                continue
            else:
                j = j + 1
print('This is the new list after removing strings: ',lists)

#5
second_element = []
for i in lists:
    second_element.append(i[2])
print(second_element)

This is the old list:  [['sam', 2, 3, 4, 5], ['good', 'build', 'jaguar', 'pencil', 'aroma', 'ink', 'jack', 'kite', 35, 67, 78, (56+6j)], ['sid', 'john', 17, 'van', 'guard', 5, 6, 7], [32, 67, 89, 34, 12], [14, 56, 'sunny', 78, 'oven']]
Index of sam is 0 
Index of good is 0 
Index of build is 1 
Index of jaguar is 2 
Index of pencil is 3 
Index of aroma is 4 
Index of ink is 5 
Index of jack is 6 
Index of kite is 7 
Index of sid is 0 
Index of john is 1 
Index of van is 3 
Index of guard is 4 
Index of sunny is 2 
Index of oven is 4 
This is the new list after removing strings:  [[2, 3, 4, 5], [35, 67, 78, (56+6j)], [17, 5, 6, 7], [32, 67, 89, 34, 12], [14, 56, 78]]
[4, 78, 6, 89, 78]


## Sets

 A Set is an unordered collection data type that is iterable, mutable, and has no duplicate elements. Python's set class represents the mathematical notion of a set.This is based on a data structure known as a hash table
 
 **Sets cant be indexed for example set_var[1] wont work



In [688]:
## Defining an empy set

set_var= set()
print(set_var)
print(type(set_var))

set()
<class 'set'>


In [747]:
set_var={1,2,3,4,3}

In [690]:
set_var # no duplicate values are printed

{1, 2, 3, 4}

In [748]:
set_var1 = {1,1,1,2,2,3,4,4,5}

In [750]:
set_var[1] # indexing, slicing operation are not possible for sets, we get an error
# if we want to perform such operations we should convert set_var1 to a list, list(set_var1)

TypeError: 'set' object is not subscriptable

In [33]:
se = {1,2,3,{1,2}} # cant provide nested set inside set

TypeError: unhashable type: 'set'

In [34]:
se = {1,2,3,[1,2]} # cant provide nested list inside set

TypeError: unhashable type: 'list'

In [37]:
se = {1,2,3,(1,2)} # can provide nested tuple inside a set

In [38]:
se

{(1, 2), 1, 2, 3}

In [39]:
type(se)

set

In [40]:
se.remove(1)

In [41]:
se

{(1, 2), 2, 3}

In [42]:
se.remove((1,2))

In [43]:
se

{2, 3}

In [46]:
se.clear() #clear the list and make it empty set

In [47]:
se

set()

In [749]:
for i in set_var1:
    print(i)
print(set_var1)

1
2
3
4
5
{1, 2, 3, 4, 5}


In [752]:
s1 = {1,2,2,3,4,5}

In [753]:
s1.pop() # here it pops the first element not the last

1

In [754]:
s1.pop(3) # here unlike list we cant choose index to pop, it will give error

TypeError: pop() takes no arguments (1 given)

In [691]:
set_var={"Avengers","IronMan",'Hitman'} # note: the output given is not ordered as we had given, it is unordered
print(set_var)
type(set_var)

{'IronMan', 'Avengers', 'Hitman'}


set

In [692]:
## Inbuilt function in sets

set_var.add("Hulk")

In [693]:
print(set_var)

{'IronMan', 'Avengers', 'Hitman', 'Hulk'}


In [30]:
set1={"Avengers","IronMan",'Hitman'}
set2={"Avengers","IronMan",'Hitman','Hulk2'}

In [31]:
'Avengers' in set1

True

In [32]:
set1[0] # indexing/slicing wont work in sets

TypeError: 'set' object is not subscriptable

In [695]:
set2.intersection_update(set1)

In [696]:
set2

{'Avengers', 'Hitman', 'IronMan'}

In [697]:
set1={"Avengers","IronMan",'Hitman'}
set2={"Avengers","IronMan",'Hitman','Hulk2'}

In [698]:
##Difference 
set2.difference(set1)

{'Hulk2'}

In [699]:
set2

{'Avengers', 'Hitman', 'Hulk2', 'IronMan'}

In [700]:
## Difference update

set2.difference_update(set1)


In [701]:
set2

{'Hulk2'}

In [48]:
s1 = {1,2,3}
s2 = {4,5,6}

In [49]:
s1 + s2 # this operation is not allowed in case of set

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [50]:
s1 * 3 #this operation is not allowed in case of set

TypeError: unsupported operand type(s) for *: 'set' and 'int'

## Dictionaries
 A dictionary is a collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets, and they have keys and values

In [702]:
dic={}

In [703]:
type(dic)

dict

In [704]:
type(dict())

dict

In [705]:
set_ex={1,2,3,4,5}

In [706]:
type(set_ex)

set

In [67]:
## Let create a dictionary

my_dict={"Car1": "Audi", "Car2":"BMW","Car3":"Mercidies Benz"}

In [51]:
my_d = {'key1':1,'key2':2,'key3':3,'key2':4,'key2':5} # if we have same key names we only get last unique key name

In [52]:
my_d

{'key1': 1, 'key2': 5, 'key3': 3}

In [53]:
my_d1 = {'key1':1,'key2':1} # we can have same value in different keys, its not a problem

In [54]:
my_d1

{'key1': 1, 'key2': 1}

In [767]:
d = {'key1' : [1,2,3,4],'key2':(4,5,6,7),'key3':{1,2,2,3,4,4,5},'key4':{1:'a',2:'b'}} 
# we can give value as a list,tuple,set and dictionary also inside a dictionary

In [766]:
d

{'key1': [1, 2, 3, 4],
 'key2': (4, 5, 6, 7),
 'key3': {1, 2, 3, 4, 5},
 'key4': {1: 'a', 2: 'b'}}

In [708]:
type(my_dict)

dict

In [64]:
##Access the item values based on keys

print(my_dict['Car1'])

Audi


In [65]:
print(my_dict.keys())

dict_keys(['Car1', 'Car2', 'Car3'])


In [66]:
'Car1' in my_dict.keys()

True

In [710]:
# We can even loop throught the dictionaries keys

for x in my_dict:
    print(x)

Car1
Car2
Car3


In [711]:
# We can even loop throught the dictionaries values

for x in my_dict.values():
    print(x)

Audi
BMW
Mercidies Benz


In [69]:
# We can also check both keys and values in form of list of tuples
for x in my_dict.items():
    print(x)

('Car1', 'Audi')
('Car2', 'BMW')
('Car3', 'Mercidies Benz')


In [713]:
## Adding items in Dictionaries

my_dict['car4']='Audi 2.0'

In [714]:
my_dict

{'Car1': 'Audi', 'Car2': 'BMW', 'Car3': 'Mercidies Benz', 'car4': 'Audi 2.0'}

In [715]:
my_dict['Car1']='MAruti' # updating Car1 with MAruti

In [716]:
my_dict

{'Car1': 'MAruti', 'Car2': 'BMW', 'Car3': 'Mercidies Benz', 'car4': 'Audi 2.0'}

In [787]:
square = {}
for i in range(1,7):
    square[i] = i**3  #i**2 is sqaured, i**3 is cubed etc...
    
print(square)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216}


In [788]:
type(square)

dict

In [796]:
l = ['samson','johnny','jammy']
di = {}

for i in l:
    di[i.upper()] = i

print(di)

{'SAMSON': 'samson', 'JOHNNY': 'johnny', 'JAMMY': 'jammy'}


In [797]:
l = ['samson','johnny','jammy']
di = {}

for i in l:
    di[i.upper()] = i.isupper()

print(di)

{'SAMSON': False, 'JOHNNY': False, 'JAMMY': False}


In [59]:
dd = {'key1':1,'key2':2}

In [60]:
dd['key2'] = dd['key2']+10

In [61]:
dd

{'key1': 1, 'key2': 12}

In [132]:
new_d = {'company':'ineuron','year':2020}

In [134]:
for i in new_d:
    if i == 'year':
        if new_d[i] >2019:
            print('Year is fine')
        else:
            print('Year needs to be updated ')

Year is fine


### Dictionary comprehension

In [800]:
{i:i**3 for i in range(1,6)}

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}

In [801]:
l = ['samson','johnny','jammy']
{i.upper():i for i in l}

{'SAMSON': 'samson', 'JOHNNY': 'johnny', 'JAMMY': 'jammy'}

### Nested Dictionary

In [717]:
car1_model={'Mercedes':1960}
car2_model={'Audi':1970}
car3_model={'Ambassador':1980}

car_type={'car1':car1_model,'car2':car2_model,'car3':car3_model}

In [718]:
car_type

{'car1': {'Mercedes': 1960},
 'car2': {'Audi': 1970},
 'car3': {'Ambassador': 1980}}

In [719]:
## Accessing the items in the dictionary

print(car_type['car1'])

{'Mercedes': 1960}


In [720]:
print(car_type['car1']['Mercedes'])

1960


In [57]:
nested = {'key1':1,'key2':[1,2,3],'key3':(1,2,3),'key4':{1,1,2}} # dictionary can hold list,tuple,set 
                                                                 #in value slot but not in key slot

In [58]:
nested

{'key1': 1, 'key2': [1, 2, 3], 'key3': (1, 2, 3), 'key4': {1, 2}}

In [ ]:
#Task
# 1. Get a sentence from wikipedia
# 2. Get Unique set of words
# 3. Create a dictionary with key as unique words and name as value
# 4. Print Tuple of all the values
# 5. Print list of all the unique keys

In [119]:
#1
sent = input('Enter a paragraph: ')

Enter a paragraph: Karnataka is a state in the south western region of India. It is the largest state in South India and sixth largest in India. It was formed on 1 November 1956, with the passage of the States Reorganisation Act. Originally known as the State of Mysore, it was renamed Karnataka in 1973. The state corresponds to the Carnatic region. Its capital and largest city is Bangalore.


In [120]:
sent

'Karnataka is a state in the south western region of India. It is the largest state in South India and sixth largest in India. It was formed on 1 November 1956, with the passage of the States Reorganisation Act. Originally known as the State of Mysore, it was renamed Karnataka in 1973. The state corresponds to the Carnatic region. Its capital and largest city is Bangalore.'

In [121]:
lower_words = sent.lower()

In [122]:
words = lower_words.split()
print(words)

['karnataka', 'is', 'a', 'state', 'in', 'the', 'south', 'western', 'region', 'of', 'india.', 'it', 'is', 'the', 'largest', 'state', 'in', 'south', 'india', 'and', 'sixth', 'largest', 'in', 'india.', 'it', 'was', 'formed', 'on', '1', 'november', '1956,', 'with', 'the', 'passage', 'of', 'the', 'states', 'reorganisation', 'act.', 'originally', 'known', 'as', 'the', 'state', 'of', 'mysore,', 'it', 'was', 'renamed', 'karnataka', 'in', '1973.', 'the', 'state', 'corresponds', 'to', 'the', 'carnatic', 'region.', 'its', 'capital', 'and', 'largest', 'city', 'is', 'bangalore.']


In [123]:
#2
unique_words = set(words)

In [124]:
print(unique_words)

{'on', 'it', '1', '1956,', 'states', 'in', 'act.', '1973.', 'was', 'largest', 'originally', 'known', 'to', 'formed', 'india.', 'a', 'with', 'renamed', 'city', 'state', 'passage', 'corresponds', 'karnataka', 'western', 'region.', 'sixth', 'bangalore.', 'its', 'region', 'capital', 'as', 'the', 'carnatic', 'south', 'is', 'of', 'november', 'and', 'india', 'mysore,', 'reorganisation'}


In [125]:
#3
unique_dict = {i:'shashank' for i in unique_words}

In [126]:
unique_dict

{'on': 'shashank',
 'it': 'shashank',
 '1': 'shashank',
 '1956,': 'shashank',
 'states': 'shashank',
 'in': 'shashank',
 'act.': 'shashank',
 '1973.': 'shashank',
 'was': 'shashank',
 'largest': 'shashank',
 'originally': 'shashank',
 'known': 'shashank',
 'to': 'shashank',
 'formed': 'shashank',
 'india.': 'shashank',
 'a': 'shashank',
 'with': 'shashank',
 'renamed': 'shashank',
 'city': 'shashank',
 'state': 'shashank',
 'passage': 'shashank',
 'corresponds': 'shashank',
 'karnataka': 'shashank',
 'western': 'shashank',
 'region.': 'shashank',
 'sixth': 'shashank',
 'bangalore.': 'shashank',
 'its': 'shashank',
 'region': 'shashank',
 'capital': 'shashank',
 'as': 'shashank',
 'the': 'shashank',
 'carnatic': 'shashank',
 'south': 'shashank',
 'is': 'shashank',
 'of': 'shashank',
 'november': 'shashank',
 'and': 'shashank',
 'india': 'shashank',
 'mysore,': 'shashank',
 'reorganisation': 'shashank'}

In [127]:
#4
tuple_of_values = []
for i in unique_dict.values():
    tuple_of_values.append(i)
print('Tuple list of values:',tuple(tuple_of_values))

Tuple list of values: ('shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank')


In [128]:
# Short way to do #4
print('Tuple list of values:',tuple(unique_dict.values()))

Tuple list of values: ('shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank', 'shashank')


In [129]:
#5
list_of_keys = []
for i in unique_dict.keys():
    list_of_keys.append(i)
print('List of keys:',list_of_keys)

List of keys: ['on', 'it', '1', '1956,', 'states', 'in', 'act.', '1973.', 'was', 'largest', 'originally', 'known', 'to', 'formed', 'india.', 'a', 'with', 'renamed', 'city', 'state', 'passage', 'corresponds', 'karnataka', 'western', 'region.', 'sixth', 'bangalore.', 'its', 'region', 'capital', 'as', 'the', 'carnatic', 'south', 'is', 'of', 'november', 'and', 'india', 'mysore,', 'reorganisation']


In [130]:
#Short way to do #5
print('List of keys:',list(unique_dict.keys()))

List of keys: ['on', 'it', '1', '1956,', 'states', 'in', 'act.', '1973.', 'was', 'largest', 'originally', 'known', 'to', 'formed', 'india.', 'a', 'with', 'renamed', 'city', 'state', 'passage', 'corresponds', 'karnataka', 'western', 'region.', 'sixth', 'bangalore.', 'its', 'region', 'capital', 'as', 'the', 'carnatic', 'south', 'is', 'of', 'november', 'and', 'india', 'mysore,', 'reorganisation']


## Tuples
 Tuple is Non Mutable or immutable, once a tuple is defined we cannot change the elements of the tuple

In [721]:
## create an empty Tuples

my_tuple=tuple()

In [722]:
type(my_tuple)

tuple

In [1]:
t = ('shashank')# if only one value is give it will consider it as string

In [2]:
type(t)

str

In [3]:
tu = ('shashank',)# if there is only one value and we need it to be considered as tuple we have add a comma next to it

In [5]:
tup = ('shashank','bhojappa')

In [6]:
type(tup)

tuple

In [4]:
type(tu)

tuple

In [723]:
my_tuple=()

In [724]:
type(my_tuple)

tuple

In [21]:
my_tuple=("Krish","Ankur","John")

In [14]:
my_tuple[0]

'Krish'

In [15]:
my_tuple[::-1]

('John', 'Ankur', 'Krish')

In [16]:
for i in my_tuple:
    print(i)

Krish
Ankur
John


In [17]:
'John' in my_tuple

True

In [23]:
my_tuple.index('John')

2

In [24]:
my_tuple.count('John')

1

In [10]:
my_tuple[0] = 'Hello' # single element inside a tuple cannot be changed/assigned becoz tuples are immutable

TypeError: 'tuple' object does not support item assignment

In [11]:
my_tuple=('Hello','World')
# we can completely change the whole list but not single element i.e my_tuple[0]='Naik' will not work

In [12]:
my_tuple[2] = 'test' # we cannot add any new data to tuples

TypeError: 'tuple' object does not support item assignment

In [728]:
print(type(my_tuple))
print(my_tuple)

<class 'tuple'>
('Hello', 'World')


In [729]:
type(my_tuple)

tuple

In [730]:
## Inbuilt function
my_tuple.count('Hello')# to check how many times that word has repeated

1

In [731]:
my_tuple.index('World')

1

In [18]:
t = (1,2,3)

In [20]:
print(max(t))
print(min(t))

3
1


In [739]:
t1 = (1,2,3)
t2 = (4,5,'sam')

t1 + t2 # this will be assigned a new memory location and not in the same memory location
# in the same memory location we cannot change anything, it is immutable there

(1, 2, 3, 4, 5, 'sam')

In [744]:
t3 = (1,2,3,'shashank')
print(t3)
print(type(t3))
t4 = list(t3) # converting tuple to a list, now we can use all functions related to list and perform many operations like
              # insert,append,extend etc...
print(list(t4))
print(type(t4))
t5 = tuple(t4) # converting list to a tuple
print(t5)
print(type(t5))

(1, 2, 3, 'shashank')
<class 'tuple'>
[1, 2, 3, 'shashank']
<class 'list'>
(1, 2, 3, 'shashank')
<class 'tuple'>


In [27]:
t1 = (1,2,3,4)

In [28]:
del(t1)

In [29]:
t1

NameError: name 't1' is not defined

# Python Function and Positional & Keyword Arguments(args & kwargs)

In [802]:
num = 24

if num % 2 == 0:
    print('Even')
else:
    print('Odd')

Even


### Creating a function

In [803]:
def even_odd(num):
    if num % 2 == 0:
        print('Even')
    else:
        print('Odd')

In [804]:
even_odd(35)

Odd


#### Scope of variable

In [33]:
r = 20 #global variable
def sum(a,b):
    r = 10 #local variable
    return a+b+r

In [34]:
sum(2,3)

15

In [35]:
r = 20
def sums(a,b):
    # here since there is no local varaiable 'r' it will take the value of r from global variable
    return a+b+r

In [36]:
sums(2,3)

25

In [37]:
def add_2(a,b):
    '''
    This is to give information to user 
    provide 2 integers separated by comma to get sum of those two integers
    '''
    return a+b

In [38]:
add_2(2,3)# if we press shift+tab now we get info about that function in Docstring

5

### print vs return

In [805]:
def hello_world():
    print('Hello Welcome')

In [806]:
hello_world()

Hello Welcome


In [807]:
val = hello_world()

Hello Welcome


In [808]:
print(val) # this function does not return any output, so here we can use return statement

None


In [809]:
def hello_world():
    return 'Hello Welcome'

In [810]:
val = hello_world()

In [811]:
print(val)

Hello Welcome


In [812]:
def add_number(num1,num2):
    return num1 + num2

In [813]:
addition = add_number(32,56)

In [814]:
addition

88

In [830]:
def test():
    a=1
    b=6
    print(a+b) # using print

In [831]:
test()

7


In [832]:
b = test()

7


In [853]:
type(b) # when we print , we get type as None type so we cant perform any operation using that value

NoneType

In [836]:
b + 1

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [854]:
def test1():
    a=1
    b=6
    return (a+b) # using return

In [855]:
c = test1()

In [856]:
type(c) # when we use return we get an integer here so we can perform other operations using the returned value

int

In [857]:
c + 1

8

### Positional and Keyword Arguments

In [815]:
def hello(name,age=30):
    print('My name is {} and age is {}'.format(name,age))

In [816]:
hello('shashank')

My name is shashank and age is 30


In [817]:
hello() # if no parameters are given we get error saying positional argument required

TypeError: hello() missing 1 required positional argument: 'name'

In [818]:
# In the above example name is Positional argument and age is Keyword argument(as it is of key value pair)

In [287]:
def hello(*args,**kwargs):  # here arges is Positional argument and kwargs is Keyword argument
    print(args)
    print(kwargs)

In [288]:
hello('Shahsank','Bhojappa', age=30, dob = 1989)

('Shahsank', 'Bhojappa')
{'age': 30, 'dob': 1989}


In [289]:
# Here Shashank and Bhojappa are considered Positional arguments 
# and age and dob are considered Keyword arguments

In [290]:
lst = ['Shahsank', 'Bhojappa']
dict_args = {'age': 30, 'dob': 1989}

In [291]:
hello(lst,dict_args)

(['Shahsank', 'Bhojappa'], {'age': 30, 'dob': 1989})
{}


In [292]:
 #But here it is showing everything as Positional arguments, so how do we do it correctly
 #we should mention which is positional and which is keyword by single and double asterix mark *(positional), **(keyword)

In [293]:
hello(*lst,**dict_args)

('Shahsank', 'Bhojappa')
{'age': 30, 'dob': 1989}


In [295]:
hello(*lst,**dict_args)

('Shahsank', 'Bhojappa')
{'age': 30, 'dob': 1989}


### kwargs should come after args, if kwargs comes before args we get an error

In [296]:
def test(x=5,y):
    return x+y

SyntaxError: non-default argument follows default argument (<ipython-input-296-08e4e7c7fbfb>, line 1)

In [827]:
listings = [1,2,3,4,5,6,7,8]

In [828]:
def even_odd_sum(listings):
    even = 0
    odd = 0
    for i in listings:
        if i%2 == 0:
            even = even + i
        else:
            odd = odd + i
    return even,odd # returning multile outputs

In [829]:
even_odd_sum(listings)

(20, 16)

In [35]:
def multiple(a,b,c):
    return a+b,a*b,b*c

In [36]:
x,y,z = multiple(4,5,6)

In [37]:
z

30

In [22]:
y

9

In [862]:
x

20

In [ ]:
z

In [46]:
x , _,z = multiple(4,5,6) # using placeholder

In [42]:
z

30

In [43]:
_

20

In [859]:
multiple(4,5)

(9, 20)

In [1143]:
# Task
# Find if the number is a prime number or not
def is_prime(num):
    for i in range(2,num):
        if num%i == 0:
            return False
            #print('{} is not prime number'.format(num))
            break

    else: # here for else loop is used
        return True
        #print('{} is a prime number'.format(num))

In [1149]:
number = int(input('Enter a number to find if its prime number or not: '))
is_prime(number)

Enter a number to find if its prime number or not: 7


True

In [1]:
def add_with_input(a,b):
    a = int(input('Enter first number to add: '))
    b = int(input('Enter second number to add: '))
    return a+b

In [2]:
add_with_input(2,3)

Enter first number to add: 3
Enter second number to add: 2


5

In [15]:
#Infinite parameter to adding function
def inf_add(*num):
    sum = 0
    for i in num:
        sum = i + sum
    return sum

In [16]:
inf_add(3,4,5,6,89,32,14)

153

In [53]:
# Adding function with infinite numbers using user input
def inf_add_inp():
    j = True
    sum = 0
    while j==True:
        a = input('Enter a number to add or q to quit: ')
        if a == 'q':
            break
        else:
            b = int(a)
            sum = b + sum
    return sum

In [54]:
inf_add_inp()

Enter a number to add or q to quit: 132
Enter a number to add or q to quit: 2
Enter a number to add or q to quit: 4
Enter a number to add or q to quit: 7
Enter a number to add or q to quit: q


145

In [49]:
def test(m):
    return m,m*2

In [54]:
 a = test([1,2,3])

In [55]:
a

([1, 2, 3], [1, 2, 3, 1, 2, 3])

In [58]:
type(a)

tuple

In [56]:
a[0]

[1, 2, 3]

In [57]:
a[1]

[1, 2, 3, 1, 2, 3]

In [62]:
def test1(m,n=30): #giving 'n' a default value of 30
    return n+m

In [63]:
test1(20)

50

In [64]:
test1(20,100) #over writing default value of 'n'

120

In [65]:
def test2(m=10,n=20):
    return m+n

In [66]:
test2()

30

In [67]:
test2(n=30)

40

In [74]:
def names(*args):
    return args

### args returns tuples

In [75]:
names('bhojappa','guru','farman','dutt') #args returns tuples

('bhojappa', 'guru', 'farman', 'dutt')

In [82]:
#Task 
# write a function that takes multiple list and give a concatination of all the list as one single list
def con_cat(*lst):
    li = []
    for i in lst:
        li = i+li
    li.sort()
    return li

In [86]:
con_cat([1,2,3],[4,5,6],[7,8,9],[10,11,12,13,14],[15,16])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [118]:
#Task 
# write a function that takes multiple list and give a concatination of all the list as one single list
# only does concatination if its a list
def con_cat(*lst):
    li = []
    [li.extend(i) for i in lst if type(i)==list] 
    return li

In [119]:
con_cat([1,2,3],[4,5,6],[7,8,9],[10,11,12,13,14],[15,16],12,'shashank')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [120]:
def test_kwargs(**kwargs):
    return kwargs

In [121]:
test_kwargs(1,2,3) # this wont works, it has to be a key value pair

TypeError: test_kwargs() takes 0 positional arguments but 3 were given

### kwargs returns dictionary

In [122]:
test_kwargs(a=1,b=2,c=3) # kwargs returns dictionary

{'a': 1, 'b': 2, 'c': 3}

In [136]:
def test3(**num):
    li = []
    for i in num.keys():
        li.append(i)
    return li
        

In [137]:
test3(a=12,b=29,c=11) #return keys

['a', 'b', 'c']

In [130]:
def test4(**num):
    li = []
    for i in num.values():
        li.append(i)
    return li

In [131]:
test4(a=12,b=29,c=11) #return values

[12, 29, 11]

In [132]:
def test5(**num):
    li = []
    for i in num.items():
        li.append(i)
    return li

In [133]:
test5(a=12,b=29,c=11) # return keys and values

[('a', 12), ('b', 29), ('c', 11)]

In [240]:
#Task 
#1 Return multiple list accordng to theri data type
#2 Return a concatinated list of List and Kwargs

def list_type_concat(*lst,**kwargs):
    lis = []
    boo = []
    di = []
    number = []
    float_num = []
    strs = []
    tup = []
    extra = []
    #kwa = []
    for i in lst:
        
        if type(i) == list:
            lis.extend(i)   
        elif type(i) == bool:
            boo.append(i)
        elif type(i) == dict:
            key_val = i.items()
            di.extend(key_val)
        elif type(i) == int:
            number.append(i)
        elif type(i) == float:
            float_num.append(i)
        elif type(i) == str:
            strs.append(i)
        elif type(i) == tuple:
            tup.append(i)
        else:
            extra.append(i)
    kwa = [i for i in kwargs.items()]
        #kwa.append(i)
    return lis,boo,di,number,float_num,strs,kwa,tup,extra,lis+kwa

In [241]:
list_type_concat(1,2,3,[10,20,30],[40,50,60],(100,200,300),{'d':44,'e':45,'f':46},True,45+6j,False,{'a':41,'b':42,'c':43},
                 3.14,91.7,34+7j,34.2,(400,500),'shashank','bhojappa',True,34,7.68,a=7,b=8,c=10,d='sam',e=[1,2,3])

([10, 20, 30, 40, 50, 60],
 [True, False, True],
 [('d', 44), ('e', 45), ('f', 46), ('a', 41), ('b', 42), ('c', 43)],
 [1, 2, 3, 34],
 [3.14, 91.7, 34.2, 7.68],
 ['shashank', 'bhojappa'],
 [('a', 7), ('b', 8), ('c', 10), ('d', 'sam'), ('e', [1, 2, 3])],
 [(100, 200, 300), (400, 500)],
 [(45+6j), (34+7j)],
 [10,
  20,
  30,
  40,
  50,
  60,
  ('a', 7),
  ('b', 8),
  ('c', 10),
  ('d', 'sam'),
  ('e', [1, 2, 3])])

In [282]:
# Task- above task in much shorter and dynamic way
def data_type_separation(*dt_types,**kwargs):
    dic = {}
    for i in dt_types:
        if type(i) in dic:
            dic[type(i)].append(i)
        else:
            dic[type(i)] = [i]
    kwa = [i for i in kwargs.items()]
    return dic,kwa

In [283]:
data_type_separation(1,2,3,[10,20,30],[40,50,60],(100,200,300),{'d':44,'e':45,'f':46},
                     True,45+6j,False,{'a':41,'b':42,'c':43},
                     3.14,91.7,34+7j,34.2,(400,500),'shashank','bhojappa',
                     True,34,7.68,a=7,b=8,c=10,d='sam',e=[1,2,3])

({int: [1, 2, 3, 34],
  list: [[10, 20, 30], [40, 50, 60]],
  tuple: [(100, 200, 300), (400, 500)],
  dict: [{'d': 44, 'e': 45, 'f': 46}, {'a': 41, 'b': 42, 'c': 43}],
  bool: [True, False, True],
  complex: [(45+6j), (34+7j)],
  float: [3.14, 91.7, 34.2, 7.68],
  str: ['shashank', 'bhojappa']},
 [('a', 7), ('b', 8), ('c', 10), ('d', 'sam'), ('e', [1, 2, 3])])

In [255]:
#Task get only the values which has a list and if that list has your name print your name is found
def get_list(**lists):
    li = []
    for i in lists.values():
        if type(i)==list:
            li.extend(i)
    if 'shashank' in li:
        return "Your name is Found"
    else:
        return "Your name is not found"
            
        

In [258]:
get_list(a=1,b=[10,20,30],c=[40,50],d=4,e=56,f = ['shashank','bhojappa',21])

'Your name is Found'

# Difference between copy.copy() and copy.deepcopy()?

The difference between shallow and deep copying is only relevant for compound objects (objects that contain other objects, like lists or class instances):

#### Shallow copy copy.copy()
A shallow copy constructs a new compound object and then (to the extent possible) inserts references into it to the objects found in the original.

#### Deep copy copy.deepcopy()
A deep copy constructs a new compound object and then, recursively, inserts copies into it of the objects found in the original.

In [185]:
l = [1,2,3,[4,5,6]]
type(l[3])

list

In [186]:
l1 = [1,2,3,4]
l2 = l1

In [187]:
l2[1] = 100

In [188]:
l2,l1 # here both lists l2 and l1 are getting changed, even though we havent modifed list l1

([1, 100, 3, 4], [1, 100, 3, 4])

#### Shallow copy

In [189]:
l1 = [1,2,3,4]
l2 = l1.copy() #Shallow Copy

In [190]:
l2[1] = 100

In [191]:
l2 #Here only l2 list is modified, even though its a copy of list l

[1, 100, 3, 4]

In [192]:
l1 # list l vaues have not changed here

[1, 2, 3, 4]

In [193]:
l1 = [[1,2,3,4],[5,6,7,8]]
l2 = l1.copy()

In [194]:
l1[1][0] = 100

In [195]:
l1,l2 # even though shallow copy is used, when its nested list shallow copy is not working, as bot li and l2 are
      # getting modified when only one of the list is modified

([[1, 2, 3, 4], [100, 6, 7, 8]], [[1, 2, 3, 4], [100, 6, 7, 8]])

#### Deep copy

In [196]:
import copy
l1 = [[1,2,3,4],[5,6,7,8]]
l2 = copy.deepcopy(l1) # Deep copy

In [197]:
l1[1][0] = 100

In [198]:
l1,l2 #Here even when we modify the value inside the nested list l1, it only modifies in list li and not in list l2

([[1, 2, 3, 4], [100, 6, 7, 8]], [[1, 2, 3, 4], [5, 6, 7, 8]])

# Iterables vs iterators

In [297]:
# List is iterable
lst = [1,2,3,4,5,6,7]

for i in lst:
    print(i)
        

1
2
3
4
5
6
7


In [298]:
iter(lst) # converting list to iterator

### In iterable as soon as it initialized all the values are saved in the memory, whereas in the case of iterator not all the values are initialized in the memory, but as soon as we call the function called 'next' then only that particular value will get initialized in the memory

In [304]:
lst1 = iter(lst)

In [300]:
lst1 # to see the values use next function, This in one way of retrieve values

In [301]:
next(lst1)

1

In [302]:
next(lst1)

2

In [303]:
next(lst1)

3

In [305]:
for i in lst1: # another way to retrieve values
    print(i)

1
2
3
4
5
6
7


# Iterators v/s Generators

In [324]:
def square(n):
    for i in range(2,n):
        return i**2 # return keyword will just return wrt to just one iteration

In [326]:
square(7) # Here we are returned the first sqaure value that is sqaured of '2' but the sqaure of other numbers are
# not returned

4

In [331]:
def square(n):
    for i in range(2,n):
        yield i**2 #yield keyword will not just return wrt just one iteration, instead it will return wrt all the iteration
                   #and it will be saving that local state values
# Here Generator is in turn creating an iterator
# when generator is used we dont get the output whe we run the function, instead we get the output
# when we either run next keyword or run it through a for loop

In [329]:
# Now when yield key is used we ge are returned all the sqaured values
for i in square(7):
    print(i)

4
9
16
25
36


In [333]:
square(7) # generator object is created

<generator object square at 0x0000025D58E40248>

In [316]:
a = square(7) 

In [318]:
next(a) #here the yield keyword(Generator) created an iterator object

4

In [319]:
next(a)

9

In [320]:
next(a)

16

In [321]:
next(a)

25

In [40]:
range(20) #range is an example for genrator object

range(0, 20)

In [41]:
for i in range(20):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


## Difference b\w Iterator and Generator
1. To create an Iterator we use iter() and to create a Generator we use function along with yield keyword 
2. Generator uses the yield keyword. It saves the local variable value
3. Generator in python helps us to write fast an compact code
4. Iterator is much more memory efficient

In [45]:
#Task
# Create a fibonacci series but when you run the function it should create a generator object and not give an output
# but when run through a for loop it gives the output or give output one by one using next function

def fib(n):
    n = int(input('Enter how many fibonacci numbers you want: '))
    a = 1
    b = 0
    for i in range(n):
        c = a+b
        b = a
        a = c
        yield c

In [46]:
fib(7)

<generator object fib at 0x000001997D2AD4C8>

In [47]:
for i in fib(7):
    print(i)

Enter how many fibonacci numbers you want: 7
1
2
3
5
8
13
21


In [341]:
fibonacci = fib(7)

In [342]:
next(fibonacci)

Enter how many fibonacci numbers you want: 7


1

In [343]:
next(fibonacci)

2

In [344]:
next(fibonacci)

3

In [345]:
next(fibonacci)

5

In [346]:
next(fibonacci)

8

In [347]:
next(fibonacci)

13

In [348]:
next(fibonacci)

21

In [349]:
next(fibonacci)

StopIteration: 

# Map function

In [351]:
def even_odd(num):
    if num%2 == 0:
        return "{} is even".format(num)
    else:
        return "{} is odd".format(num)

In [352]:
even_odd(11)

'11 is odd'

In [353]:
even_odd(10)

'10 is even'

In [378]:
lst = [1,2,3,4,15,45,34,12,36,76,23,14,52]

In [355]:
map(even_odd,lst)

In [356]:
list(map(even_odd,lst))

['1 is odd',
 '2 is even',
 '3 is odd',
 '4 is even',
 '15 is odd',
 '45 is odd',
 '34 is even',
 '12 is even',
 '36 is even',
 '76 is even',
 '23 is odd',
 '14 is even',
 '52 is even']

In [379]:
list(map(lambda x : x**2,lst))

[1, 4, 9, 16, 225, 2025, 1156, 144, 1296, 5776, 529, 196, 2704]

In [380]:
a = [1,2,3]
b = [21,32,45]
c = [2,5,6,7,8,9] # c has extra values, which will not be added

list(map(lambda x,y,z: x+y+z,a,b,c))

[24, 39, 54]

# Lambda Function
A function with no name used only for single line functions 

In [357]:
def addition(a,b):
    return a+b

In [358]:
addition(4,5)

9

In [359]:
adding = lambda a,b:a+b

In [360]:
adding(6,5)

11

In [361]:
def even(num):
    if num % 2 == 0:
        return True

In [362]:
even(22)

True

In [363]:
even = lambda x:x%2==0

In [364]:
even(11)

False

In [365]:
even(20)

True

In [366]:
def addition(x,y,z):
    return x+y+z

In [367]:
addition(2,4,7)

13

In [368]:
add_lambda = lambda x,y,z: x+y+z

In [369]:
add_lambda(6,8,9)

23

# Filter function

In [370]:
def even(num):
    if num%2==0:
        return True

In [371]:
lst = [1,2,3,4,5,6,7,8,9]

In [372]:
filter(even,lst) #first parameter function(even), second parameter iterable(lst)

In [373]:
list(filter(even,lst))

[2, 4, 6, 8]

In [374]:
def even_odd(num):
    if num%2 == 0:
        return True

In [375]:
list(map(even_odd,lst)) # in case of map function we get None where else is not defined, wheras in filter function
# only where it is true it is displayed

[None, True, None, True, None, True, None, True, None]

In [376]:
filter(lambda x:x%2==0,lst) # using lambda to make it much simpler

In [377]:
list(filter(lambda x:x%2==0,lst))

[2, 4, 6, 8]

# OOPS Concept

In [397]:
class Car:
    pass

In [398]:
car1 = Car()

In [399]:
car1.windows=5
car1.doors=4

In [400]:
print(car1.windows)

5


In [401]:
print(car1.doors)

4


In [402]:
car2 = Car()

In [403]:
car2.windows=3

In [404]:
car2.doors=2

In [405]:
print(car2.windows)

3


In [406]:
car2.engine_type='Petrol'

In [407]:
print(car2.engine_type)

Petrol


### If we have not fixed the number of attributes, any number of attributes can be created by the developer, which is a bad approach, in order to make a right approach what we do is, we use __init__ constructor.
### Constructor is basically used in order to initialize how many number of properties are getting used in that particular class

In [89]:
class Cars:
    def __init__(self,window,door,enginetype):
        self.window = window
        self.door = door
        self.enginetype = enginetype
    def self_driving(self):
        return "This ia a {} car".format(self.enginetype)
    def manual_car(self,mileage):
        self.mileage = mileage
        return "This is a {door} door with mileage {mileage}".format(door=self.door,mileage=self.mileage)
    def __str__(self):
        return 'This is a Cars class we are using which has {} windows, {} doors and is {} engine'.format(
        self.window,self.door,self.enginetype)

In [2]:
audi = Cars() # if properties are not mentioned it will give an positional arguments error saying 
# 'window', 'door', and 'enginetype' are required


TypeError: __init__() missing 3 required positional arguments: 'window', 'door', and 'enginetype'

## In here Cars() is a class and audi and bmw are objects, audi and bmw are objects of Cars class

In [90]:
audi = Cars(4,5,'Petrol')

In [91]:
audi.self_driving()

'This ia a Petrol car'

In [50]:
print(audi) # this comes when we are not using __str__

In [61]:
print(audi) # here we are using __str__ and over riding

This is a Cars class we are using which has 4 windows, 5 doors and is Petrol engine


In [92]:
audi.__dict__

{'window': 4, 'door': 5, 'enginetype': 'Petrol'}

In [62]:
bmw = Cars(3,2,'Diesel')

In [63]:
print(bmw)

This is a Cars class we are using which has 3 windows, 2 doors and is Diesel engine


In [43]:
print(audi.window)

4


In [44]:
print(bmw.window)

3


In [45]:
print(bmw.door)

2


In [46]:
audi.manual_car(18)

'This is a 5 door with mileage 18'

In [462]:
class Mammals:
    def __init__(self,legs,blood_type,wild,domestic,herbivore,carnivore):
        self.legs = legs
        self.blood_type = blood_type
        self.wild = wild
        self.domestic = domestic
        self.herbivore = herbivore
        self.carnivore = carnivore

In [463]:
lion = Mammals(4,'warm blooded',True,False,False,True)

In [466]:
lion.legs

4

In [464]:
pig = Mammals(4,'warm blooded',False,True,True,False)

In [467]:
pig.wild

False

In [465]:
cow = Mammals(4,'warm blooded',False,True,True,False)

In [468]:
cow.blood_type

'warm blooded'

# Inheritance

In [71]:
# Here all the class variables are Public
class Car:
    def __init__(self,window,door,enginetype):
        self.window = window
        self.door = door
        self.enginetype = enginetype
    def drive(self):
        print('The Person drives the car')
    def __str__(self):
        return "This is a car."

In [72]:
car = Car(4,5,"Diesel")

In [73]:
print(car) #this is coming from __str__ method

This is a car.


In [74]:
dir(car)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'door',
 'drive',
 'enginetype',
 'window']

In [75]:
car.enginetype

'Diesel'

In [76]:
car.drive()

The Person drives the car


In [88]:
class audi(Car):
    def __init__(self,window,door,enginetype,enableai): # parameters from parent class and new parameter
        super().__init__(window,door,enginetype)#parameters from parent class
        self.enableai=enableai
    def selfdriving(self):
        print("Audi supports Self Driving")
    def __str__(self): # this is Method Over riding
        return 'Brand name is Audi'

In [89]:
audiQ7 = audi(5,5,'Diesel',True)

#### Method Overiding

In [90]:
print(audiQ7) # the __str__ method from child class audi is overiding the __str__ method from parent class Car

Brand name is Audi


In [91]:
print(car)

This is a car.


In [436]:
dir(audiQ7) #All parameters of parent class are availbale

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'door',
 'drive',
 'enableai',
 'enginetype',
 'selfdriving',
 'window']

In [87]:
audiQ7.window

5

In [11]:
audiQ7.door

5

In [439]:
audiQ7.enableai

True

In [440]:
audiQ7.drive()

The Person drives the car


In [441]:
audiQ7.selfdriving()

Audi supports Self Driving


# Method Overiding

In [103]:
class person:
    def __init__(self,a,b,c):
        self.a = a
        self.b = b
        self.c = c
    def __str__(self):
        return 'My name is shashnak'

In [104]:
p = person(3,4,5)

In [105]:
print(p)

My name is shashnak


In [106]:
class student(person):
    def __init__(self,student_id,*args):
        super(student,self).__init__(*args)
        self.student_id = student_id
    def __str__(self):
        return super(student,self).__str__() + ' I am a student'

In [107]:
s = student(4,5,6,7)

In [108]:
print(s) # here we can see that in the student class it is not only overiding __str__ method from person class
         # it also inheriting __str__ method from person class and appending it in student class

My name is shashnak I am a student


### Second way of initializing the inheritence(change in using super())

In [113]:
class Mammals:
    def __init__(self,legs,blood_type,wild,domestic,herbivore,carnivore):
        self.legs = legs
        self.blood_type = blood_type
        self.wild = wild
        self.domestic = domestic
        self.herbivore = herbivore
        self.carnivore = carnivore
    

In [125]:
class Tiger(Mammals):
    def __init__(self,stripe_color,diet,population,*args):
        super(Tiger,self).__init__(*args)
        self.stripe_color = stripe_color
        self.diet = diet
        self.population = population

In [130]:
class Horse(Mammals):
    def __init__(self,speciality,*args):
        super(Horse,self).__init__(*args)
        self.speciality = speciality

In [135]:
class Sheep(Mammals):
    def __init__(self,used_for,*args):
        super(Sheep,self).__init__(*args)
        self.used_for = used_for

In [126]:
regular_tiger = Tiger('orange-black','deer',2000,4,'warm blooded',True,False,False,True)

In [127]:
white_tiger = Tiger('white-black','deer',200,4,'warm blooded',True,False,False,True,)

In [128]:
regular_tiger.stripe_color

'orange-black'

In [129]:
white_tiger.population

200

In [131]:
horse1 = Horse('Runs fast',4,'warm blooded',False,True,True,False)

In [132]:
horse2 = Horse('Jumps higher',4,'warm blooded',False,True,True,False)

In [133]:
horse1.speciality

'Runs fast'

In [134]:
horse2.speciality

'Jumps higher'

In [136]:
sheep1 = Sheep('used for wool',4,'warm blooded',False,True,True,False)

In [137]:
sheep2 = Sheep('used for meat',4,'warm blooded',False,True,True,False)

In [138]:
sheep1.used_for

'used for wool'

In [139]:
sheep2.used_for

'used for meat'

In [35]:
class Cars:
    def __init__(self,window,door,enginetype):
        self.window = window
        self.door = door
        self.enginetype = enginetype
    def self_driving(self):
        return "This ia a {} car".format(self.enginetype)
    def manual_car(self,mileage):
        self.mileage = mileage
        return "This is a {door} door with mileage {mileage}".format(door=self.door,mileage=self.mileage)

In [36]:
audi = Cars(3,4,'Petrol')

In [37]:
audi.self_driving()

'This ia a Petrol car'

In [38]:
audi.manual_car(12)

'This is a 4 door with mileage 12'

# Multiple Inheritance

In [59]:
class a:
    def __init__(self,age):
        self.age = age
    def test(self):
        print('My First name is Shashank and age is {}'.format(self.age))
    def test1(self):
        print('My Full name is Shashank Bhojappa')

        
class b:
    def __init__(self,reg_num):
        self.reg_num = reg_num
    def test(self):
        print('My Last name is Bhojappa and register number is {}'.format(self.reg_num))
    def test2(self):
        print('My Short name is shashi')

        
class c(a,b): #multiple inheritence is used here from class a and class b
    
    obja = a(18)
    objb = b(50)
    obja.test()# this gives 'My First name is Shashank and age is 18'
    obja.test1()# this gives 'My Full name is Shashank Bhojappa'
    objb.test()# this gives 'My Last name is Bhojappa and register number is 50'
    objb.test2()# this gives 'My Short name is shashi'

    
    
objc = c(20)
objc.test() # here since both class a and class b have same method names test()
            # this gives 'My First name is Shashank and age is 20' the the first instance of parent class 
            # mentioned in class 'c'
            # that is c(a,b) if we change it to c(b,a) we will get 'My Last name is Bhojappa and register number is 20'

objc.test1()# this gives 'My Full name is Shashank Bhojappa'
objc.test2()# this gives 'My Short name is shashi'

My First name is Shashank and age is 18
My Full name is Shashank Bhojappa
My Last name is Bhojappa and register number is 50
My Short name is shashi
My First name is Shashank and age is 20
My Full name is Shashank Bhojappa
My Short name is shashi


# Public Protected and Private

 Public can be accessed from anywhere
 
 Protected can only be accessed from sub class or child class
 
 Private cannot be accessed

In [64]:
# Here all the class variables are Public
class Car:
    def __init__(self,window,door,enginetype):
        self.window = window
        self.door = door
        self.enginetype = enginetype

In [65]:
audi=Car(4,5,'Diesel')

In [66]:
dir(audi)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'door',
 'enginetype',
 'window']

In [93]:
# Here all the class variables are Protected
class Car:
    def __init__(self,window,door,enginetype):
        self._window = window
        self._door = door
        self._enginetype = enginetype

In [94]:
audi = Car(4,4,'Diesel')

In [95]:
dir(audi)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_door',
 '_enginetype',
 '_window']

In [96]:
audi.window #this will give an error now

AttributeError: 'Car' object has no attribute 'window'

In [97]:
audi._window #we will have to use '_window' to use protected

4

In [98]:
audi.__dict__ # here the variable is stored as '_window':4

{'_window': 4, '_door': 4, '_enginetype': 'Diesel'}

In [70]:
class Truck(Car):
    def __init__(self,window,door,enginetype,horsepower):
        super().__init__(window,door,enginetype)
        self.horsepower=horsepower

In [71]:
truck=Truck(4,4,'Diesel',4000)
dir(truck)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_door',
 '_enginetype',
 '_window',
 'horsepower']

In [101]:
# Here all the class variables are Private
class Car:
    def __init__(self,window,door,enginetype):
        self.__window = window
        self.__door = door
        self.__enginetype = enginetype

In [102]:
audi = Car(4,4,'Diesel')

In [103]:
audi.window

AttributeError: 'Car' object has no attribute 'window'

In [104]:
audi.__window # this wont give the result

AttributeError: 'Car' object has no attribute '__window'

In [105]:
dir(audi) # in private we cannot see window,door and enginetype parameters
# instead we see '_Car__door','_Car__enginetype','_Car__window'
# This means that this variable cannot be accessed or modified from outside of this particular class

['_Car__door',
 '_Car__enginetype',
 '_Car__window',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [106]:
audi.__dict__ #here the variable is stored by appending class name in front of variable name '_Car__window'
# this means its Private

{'_Car__window': 4, '_Car__door': 4, '_Car__enginetype': 'Diesel'}

In [107]:
audi._Car__window # now it will give

4

# Encapsulation

In inheritence we are trying to inherit the properties of a parent class, for example assume we have a 3 classes tyre,enngine and body, in this case to have a Car class we need to take tyre, engine and body class as parent class and then inherit all their properties, what if we dont want to achieve these things by inheritence, we dont want to use tyre,engine and body class as a parent class and we need a different approach. Lets assume someone else has already created these 3 classes(tyre,engine and body)

'tyr' is an object of tyre class, 'eng' is an object of engine class and 'bod' is an object of  body class, Here we are just using these objects and calling it inside a Car class

instead of passing our own data we are passing the object here. we are just reutilizing those classes written by others, we may not even know what those classes does and how it works. we are not supposed to worry about how the tyre class,engine class and the body class works, all we are doing is call these objects inisde a Car class.

we can see that there is no Parent and Chile relation anywhere

for example when we are using Pandas, we will import pandas but we dont know what code or function have they written inside those classes, we just import and utilize the functions, methods implemented inside the respective classes

In [140]:
class tyre:
    def __init__(self,brand,opt_pre,dia):
        self.brand = brand
        self.opt_pre = opt_pre
        self.dia = dia
    def __str__(self):
        return str(self.brand)+ ' ' + str(self.opt_pre)+' '+ str(self.dia)

In [144]:
tyr = tyre('MRF',32,80)

In [145]:
print(tyr)

MRF 32 80


In [163]:
class engine:
    def __init__(self,hp,torq,type):
        self.hp = hp
        self.torq = torq
        self.type = type
    def __str__(self):
        return str(self.hp)+' '+str(self.torq)+' '+str(self.type)

In [164]:
eng = engine(350,45,"Petrol")

In [165]:
print(eng)

350 45 Petrol


In [148]:
class body:
    def __init__(self,length,width,height):
        self.length = length
        self.width = width
        self.height = height
    def __str__(self):
        return str(self.length)+' '+str(self.width)+' '+str(self.height)

In [149]:
bod = body(1800,560,450)

In [150]:
print(bod)

1800 560 450


In [166]:
class Car:
    def __init__(self,t,e,b):
        self.t = t
        self.e = e
        self.b = b
    def __str__(self):
        return str(self.t)+' '+str(self.e)+' '+str(self.b)

## Composite encapsulation

Here  in the final class that is Car class we have to call object of all the variable which we are going to cal inside the class, that is tyr,eng and bod in this example, so only we have initialized variables t,e and b in Car class, we are using those as place holders

In composite encapsulation we always try to provide object of the classes we have already implemented that is tyr,eng and bod in this example

In [167]:
car = Car(tyr,eng,bod) # here tyr,eng and bod are objects of tyre,engine and body class

In [168]:
print(car)

MRF 32 80 350 45 Petrol 1800 560 450


## Dynamic encapsulation

we can provide of combination of object data and own input data for some of the variables we have initialized and this kind of encapsulation is called Dynamic encapsulation, where we are trying to provide object as well as own local input

In [171]:
car1 = Car(tyr,eng,'test2') # we can provide combination of object data and own input data

In [172]:
print(car1)

MRF 32 80 350 45 Petrol test2


# Polymorphism

Here in this example the function behaves differently according to different situations

when a string is passed it will perform concatenation, when a integer is passed it will perform Addition operation, when a list is passed it performs extend operation. It is behaving differently under different conditions and this is concept called Polymorphism. Here add function is performing multiple role in different environment

In [173]:
#Example 1
def add(a,b):
    return a+b

In [176]:
add('abc','defg')

'abcdefg'

In [177]:
add(3,4)

7

In [178]:
add([1,2,3,4],[5,6,7,8])

[1, 2, 3, 4, 5, 6, 7, 8]

In [181]:
#Example 2
def mul(a,b):
    return a*b

In [182]:
mul('abc',3)

'abcabcabc'

In [183]:
mul(3,4)

12

In [184]:
mul([1,2,3],5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

# File Handling

### Creating a new file

In [199]:
%%writefile test.txt
My name is Shashank

Writing test.txt


In [200]:
pwd() # file is saved in this path

'E:\\Full_Stack_data_science\\Python'

### Opening a file

'r'       open for reading (default)

'w'       open for writing, truncating the file first

'x'       create a new file and open it for writing

'a'       open for writing, appending to the end of the file if it exists

'b'       binary mode

't'       text mode (default)

'+'       open a disk file for updating (reading and writing)

'U'       universal newline mode (deprecated)

In [202]:
f = open('E:\\Full_Stack_data_science\\Python\\test.txt')
f

<_io.TextIOWrapper name='E:\\Full_Stack_data_science\\Python\\test.txt' mode='r' encoding='cp1252'>

### Read file

In [203]:
f.read()

'My name is Shashank\n'

In [204]:
f.seek(4)# it will set the cursor to 4th index, so next time we read a file it reads the file from that index

4

In [205]:
f.read()

'ame is Shashank\n'

In [48]:
f1 = open('E:\\Full_Stack_data_science\\Python\\test.txt',mode = 'w+') #this writes a new data in the file
                                                                       #by truncating the last data and update it
f1.write('My First name is Shashank \nMy Lastname is Bhojappa \nMy short nam is Shashi')

74

In [212]:
f1.read() # this will be empty because after write operation the cursor will be in last index, we need to bring it to 
          # 0th index by using seek

''

In [213]:
f1.seek(0)

0

In [214]:
f1.read() # here we cant see all the lines line by line, instead it just denotes \n to represent next line

'My First name is Shashank \nMy Lastname is Bhojappa \nMy short nam is Shashi'

In [215]:
for i in open('E:\\Full_Stack_data_science\\Python\\test.txt'): #to read lines line by line
    print(i)

My First name is Shashank 

My Lastname is Bhojappa 

My short nam is Shashi


In [49]:
f1 = open('E:\\Full_Stack_data_science\\Python\\test.txt',mode = 'a+') #this appends a new data in the 
#file at the end                                                                
f1.write('\nMy other short name is BC')

26

In [226]:
f1.read()

''

In [227]:
f1.seek(0)

0

In [228]:
f1.read()

'My First name is Shashank \nMy Lastname is Bhojappa \nMy short nam is Shashi\nMy other short name is BC'

In [229]:
for i in open('E:\\Full_Stack_data_science\\Python\\test.txt'): #to read lines line by line
    print(i)

My First name is Shashank 

My Lastname is Bhojappa 

My short nam is Shashi

My other short name is BC


In [50]:
f1.readline()#readline() reads line by line

'My First name is Shashank \n'

In [51]:
f1.readline()

'My Lastname is Bhojappa \n'

In [230]:
from io import StringIO # by using StringIO we can perform file like operation

In [231]:
s = input()

shashank Bhojappa


In [232]:
s1 = StringIO(s)

In [234]:
print(type(s))
print(type(s1))

<class 'str'>
<class '_io.StringIO'>


In [235]:
#now if we press shift+tab after s1. we get a list of file operations that we can do

In [236]:
s1.read()

'shashank Bhojappa'

In [237]:
s1.seek(3)

3

In [238]:
s1.read()

'shank Bhojappa'

In [240]:
s1.write('My name is shashank')

19

In [241]:
s1.read()

''

In [242]:
s1.seek(0)

0

In [243]:
s1.read()

'shashank BhojappaMy name is shashank'

In [55]:
import os

In [56]:
os.listdir()

['.ipynb_checkpoints',
 'assignment_1.ipynb',
 'assignment_10.ipynb',
 'assignment_11.ipynb',
 'assignment_12.ipynb',
 'assignment_13.ipynb',
 'assignment_2.ipynb',
 'assignment_3.ipynb',
 'assignment_4.ipynb',
 'assignment_5.ipynb',
 'assignment_6.ipynb',
 'assignment_8.ipynb',
 'assignment_9.ipynb',
 'Python-notes.ipynb',
 'test.txt']

In [60]:
pwd()

'E:\\Full_Stack_data_science\\Python'

In [59]:
os.listdir('E:\\Full_Stack_data_science\\Python')

['.ipynb_checkpoints',
 'assignment_1.ipynb',
 'assignment_10.ipynb',
 'assignment_11.ipynb',
 'assignment_12.ipynb',
 'assignment_13.ipynb',
 'assignment_2.ipynb',
 'assignment_3.ipynb',
 'assignment_4.ipynb',
 'assignment_5.ipynb',
 'assignment_6.ipynb',
 'assignment_8.ipynb',
 'assignment_9.ipynb',
 'Python-notes.ipynb',
 'test.txt']

In [ ]:
os.mkdir('test')# create new directory/folder

In [66]:
if 'test.txt' in os.listdir():
    print('File is available in this directory')
    f = open('test.txt',mode='a+')
    f.write('\nMy other short name is BC')#appends this text to the file test.txt
else:
    print('File is not available in this directory')

File is available in this directory


In [191]:
if not os.path.isdir('test'): #this will check if folder name test is already there or not and if its there it wont
    os.mkdir('test')         # create but if 'test' folder is not there already then it will create a 'test' folder

In [ ]:
#Task
#1. Create a new Directory
#2. Create 10 txt files and write some data into the file at the same time
#3. Read all the 10 files and put all the data into one list and print the list
#4. Create a new file and write all the data from all the 10 files into this new file
#5. move all the 10 text files except the new file created to a new folder

In [1]:
import os

In [2]:
import shutil

In [3]:
#1
folder_name = ''
if not os.path.isdir('task'): 
    os.mkdir('task')
    folder_name = '\\task\\'
    os.chdir(os.getcwd()+'\\'+folder_name) #this changes the current directory from
                    #'E:\\Full_Stack_data_science\\Python' to 'E:\\Full_Stack_data_science\\Python\\task'
    c = os.getcwd()
    print(c)
#2    
for i in range(1,11):
    Fname = 'test'+str(i)+'.txt'
    f = open(c+'\\'+str(Fname),mode = 'w')
    f.write('this is task '+str(i))
    f.close()
#3
all_list = []
for i in range(1,11):  
    f = open(c+'\\'+'test'+str(i)+'.txt',mode = 'r')
    print(f.read())
    f.seek(0)
    all_list.append(f.read())
    f.close()
print(all_list)
#4
all_data = open(c+'\\'+'newfile.txt','w')
for i in all_list:
    all_data.write(i+'\n')
all_data.close()

current_dir = os.listdir(c)
print(current_dir)
#5
for i in range(1,11):
    if not os.path.isdir('separated_files'):
        os.mkdir('separated_files')
    shutil.move(c+'\\'+'test{}.txt'.format(i),str(c)+'\\separated_files')
os.chdir('E:\\Full_Stack_data_science\\Python')

E:\Full_Stack_data_science\Python\task
this is task 1
this is task 2
this is task 3
this is task 4
this is task 5
this is task 6
this is task 7
this is task 8
this is task 9
this is task 10
['this is task 1', 'this is task 2', 'this is task 3', 'this is task 4', 'this is task 5', 'this is task 6', 'this is task 7', 'this is task 8', 'this is task 9', 'this is task 10']
['newfile.txt', 'test1.txt', 'test10.txt', 'test2.txt', 'test3.txt', 'test4.txt', 'test5.txt', 'test6.txt', 'test7.txt', 'test8.txt', 'test9.txt']


In [4]:
pwd

'E:\\Full_Stack_data_science\\Python'

In [5]:
# Task

# download Assignment_1.docx,Assignment_2.docx,Assignment_3.docx from 1st section and then download
# Assignment_1.docx,Assignment_2.docx,Assignment_3.docx from 2nd section, since the file names are same it will be 
# 2nd section will be stored as Assignment_1 (1).docx ,Assignment_2 (1).docx,Assignment_3 (1).docx in Downloads folder

#1. Make a new folder wherever we want(Destination folder) and move all these assignment files to that new folder
#2. Rename all the files accordingly
#3. Consolidate all the assignment files into a single file

In [6]:
import shutil
import os

folder_name = 'Assignment'
source_path = input('Enter the folder path where assignment files are located: ')
#C:\\Users\\Shashank\\Downloads
dest_path = input('Enter the folder path where assignments need to be moved: ')
# E:\\Full_Stack_data_science\\Python
os.chdir(source_path)

Enter the folder path where assignment files are located: C:\\Users\\Shashank\\Downloads
Enter the folder path where assignments need to be moved: E:\\Full_Stack_data_science\\Python


In [7]:
os.mkdir(dest_path+'\\'+folder_name) # make new directory in destination path

In [8]:
for i in os.listdir():
    if 'Assignment' in i: # check if word'Assignment' is present in list of directories
        if ('docx' in i) and (os.path.isfile(i) == True): # check if its a docx file and if it is a file (not a folder) 
            shutil.move(i,dest_path+'\\'+folder_name) # move the file to destination foler path

In [9]:
os.chdir(dest_path+'\\'+folder_name) # change working directory to destination folder directory

In [10]:
pwd

'E:\\Full_Stack_data_science\\Python\\Assignment'

In [11]:
for i in os.listdir():
    if '(' in i: #  check if '(' is present in the moved file
        main = int(i[11]) #extract the assignment number
        sub = int(i[14]) # extract the section number(number of duplicate copies)
        os.rename(i,'Asignment_{}_section_{}.docx'.format(main,sub)) # rename the files ex. Assignment_1section_0
    else: #if '(' is not present then run this
        main = int(i[11])
        sub = 0
        os.rename(i,'Asignment_{}_section_{}.docx'.format(main,sub))

In [12]:
!pip install python-docx
from docx import Document
import docx

In [13]:
# this function goes the through the docx file and extracts all the paragraphs and makes a list of paragraph
#but we are not using this function instead we are using just its method 
def getText(filename):
    doc = docx.Document(filename)
    fullText = []
    for para in doc.paragraphs:
        fullText.append(para.text)
        doc.add_page_break()
    return '\n'.join(fullText)

In [14]:
os.listdir()

['Asignment_1section_0.docx',
 'Asignment_1section_1.docx',
 'Asignment_1section_2.docx',
 'Asignment_2section_0.docx',
 'Asignment_2section_1.docx',
 'Asignment_3section_0.docx',
 'Asignment_3section_1.docx']

In [15]:
for i in os.listdir():
    filename_ext = i.split('.')# splits the filename with extension
    filename = filename_ext[0]# retrieves only the filename
    
    doc = docx.Document(i)  # this the method we are aking from getText() function
    data = ""
    fullText = []# this the method we are aking from getText() function
    for para in doc.paragraphs:# this the method we are aking from getText() function
        fullText.append(para.text) # this the method we are aking from getText() function
        data = '\n'.join(fullText)# this the method we are aking from getText() function
   
    try:
        my_doc = docx.Document('consolidated'+'.docx') # open the consolidated.docx file
    except:  
        my_doc = docx.Document() # if the consolidated.docx file is not already present, create a new file
        my_doc.save('consolidated'+'.docx')  

    my_doc.add_page_break()  # add a page break   
    my_doc.add_paragraph('\n\n filename is '+filename) 
    my_doc.add_paragraph(data)
    my_doc.save('consolidated'+'.docx')

In [ ]:
# Task

# download Assignment_1.docx,Assignment_2.docx,Assignment_3.docx from 1st section and then download
# Assignment_1.docx,Assignment_2.docx,Assignment_3.docx from 2nd section, since the file names are same in  
# 2nd section it will be stored as Assignment_1 (1).docx ,Assignment_2 (1).docx,Assignment_3 (1).docx in Downloads folder

# Similarly download Programming_Asignment_1.docx,Programming_Asignment_2.docx,Programming_Asignment_3.docx 
#from 1st section and then download Programming_Asignment_1.docx,Programming_Asignment_2.docx,
#Programming_Asignment_3.docx from 2nd section, since the file names are same it will be 
# 2nd section will be stored as Programming_Asignment_1 (1).docx,Programming_Asignment_2 (1).docx,
#Programming_Asignment_3 (1).docx in Downloads folder

#1. Make a new folder wherever we want(Destination folder) and move all these assignment files to that new folder
#2. Rename all the files accordingly
#3. Consolidate all the assignment files into 2 files, one for consolidating all the Assignments and
# other one for consolidating all the Programming_Assignments 

In [16]:
!pip install python-docx
import shutil
import os
from docx import Document
import docx

folder_name = 'Assignment_test'
source_path = input('Enter the folder path where assignment files are located: ')
#C:\\Users\\Shashank\\Downloads
dest_path = input('Enter the folder path where assignments need to be moved: ')
# E:\\Full_Stack_data_science\\Python
os.chdir(source_path)

os.mkdir(dest_path+'\\'+folder_name)

Enter the folder path where assignment files are located: C:\\Users\\Shashank\\Downloads
Enter the folder path where assignments need to be moved: E:\\Full_Stack_data_science\\Python


In [17]:
def rename(file_ext):
    if 'Programming' in file_ext:
        if '(' in file_ext:
            main = int(file_ext[23])
            sub = int(file_ext[26])
            filename_ext = file_ext.split('_')
            filename = filename_ext[0]
            os.rename(file_ext,filename+'_{}section_{}.docx'.format(main,sub))
        else:
            main = int(file_ext[23])
            sub = 0
            filename_ext = file_ext.split('_')
            filename = filename_ext[0]
            os.rename(file_ext,filename+'_{}section_{}.docx'.format(main,sub))
    else:
        if '(' in file_ext:
            main = int(file_ext[11])
            sub = int(file_ext[14])
            filename_ext = file_ext.split('_')
            filename = filename_ext[0]
            os.rename(file_ext,filename+'_{}_section_{}.docx'.format(main,sub))
        else:
            main = int(file_ext[11])
            sub = 0
            filename_ext = file_ext.split('_')
            filename = filename_ext[0]
            os.rename(file_ext,filename+'_{}_section_{}.docx'.format(main,sub)) 

In [18]:
def consolidate(file_ext):
    filename_ext = file_ext.split('.')
    filename = filename_ext[0]
    
    doc = docx.Document(i)  
    data = ""
    fullText = []
    for para in doc.paragraphs:
        fullText.append(para.text) 
        data = '\n'.join(fullText)
    if 'Programming' in file_ext: 
        try:
            my_doc = docx.Document('Programming_consolidated'+'.docx') 
        except:  
            my_doc = docx.Document()
            my_doc.save('Programming_consolidated'+'.docx')  

        my_doc.add_page_break()    
        my_doc.add_paragraph('\n\n filename is '+filename) 
        my_doc.add_paragraph(data)
        my_doc.save('Programming_consolidated'+'.docx')
    else:
        try:
            my_doc = docx.Document('consolidated'+'.docx') 
        except:  
            my_doc = docx.Document()
            my_doc.save('consolidated'+'.docx')  

        my_doc.add_page_break()    
        my_doc.add_paragraph('\n\n filename is '+filename) 
        my_doc.add_paragraph(data)
        my_doc.save('consolidated'+'.docx')

In [19]:
for i in os.listdir():
    if 'Assignment' in i:
        if ('docx' in i) and (os.path.isfile(i) == True):
            shutil.move(i,dest_path+'\\'+folder_name)
            
os.chdir(dest_path+'\\'+folder_name)

for i in os.listdir():
    rename(i)

for i in os.listdir():
    consolidate(i)

# Exception Handling

In [ ]:
try:
    # code block where exception can occur
except:
    # print out the message

In [1]:
a = b

NameError: name 'b' is not defined

In [2]:
try:
    a=b
except:
    print('Some problem has occured')# customized message

Some problem has occured


In [3]:
try:
    a=b
except Exception as ex:
    print(ex)

name 'b' is not defined


In [4]:
try:
    a=b
except NameError as ex1:
    print('The user have not defined the variable') # Name error is derived from Exeption so child should be on top
except Exception as ex:
    print(ex)

The user have not defined the variable


In [5]:
try:
    a=1
    b='s'
    c=a+b
except NameError as ex1:
    print('The user have not defined the variable') # Name error is derived from Exeption so child should be on top
    # if NameError is not caught it will go to Exception
except Exception as ex:
    print(ex)

unsupported operand type(s) for +: 'int' and 'str'


In [6]:
a=1
b='s'
c=a+b

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [7]:
try:
    a=1
    b='s'
    c=a+b
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') # if NameEroor is not caught it will come to TypeError
except Exception as ex:
    print(ex)

Try to make the data type similar


In [31]:
s  = int(input('enter: '))

enter: e


ValueError: invalid literal for int() with base 10: 'e'

In [22]:
try:
    a=int(input('Enter the first number: '))
    b=int(input('Enter the second number: '))
    c=a/b
    d=a*b
    e=a+b
    print(c)
    print(d)
    print(e)
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') # if NameError is not caught it will come to TypeError
except ValueError as ex3:
    print('Try to give an integer input')# if TypeError is not caught it will come to ValueError
except Exception as ex:
    print(ex)

Enter the first number: e
Try to give an integer input


In [23]:
try:
    a=int(input('Enter the first number: '))
    b=int(input('Enter the second number: '))
    c=a/b
    d=a*b
    e=a+b
    print(c)
    print(d)
    print(e)
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') # if NameError is not caught it will come to TypeError
except ValueError as ex3:
    print('Try to give an integer input')# if TypeError is not caught it will come to ValueError
except Exception as ex:
    print(ex)

Enter the first number: 12
Enter the second number: 6
2.0
72
18


In [24]:
try:
    a=int(input('Enter the first number: '))
    b=int(input('Enter the second number: '))
    c=a/b
    d=a*b
    e=a+b
    print(c)
    print(d)
    print(e)
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') # if NameEroor is not caught it will come to TypeError
except ValueError as ex3:
    print('Try to give an integer input')
except Exception as ex:
    print(ex)

Enter the first number: 12
Enter the second number: 0
division by zero


In [13]:
# here division by zero error is handled by exception
# what if we want to handle it with our own message

In [14]:
12/0

ZeroDivisionError: division by zero

In [25]:
try:
    a=int(input('Enter the first number: '))
    b=int(input('Enter the second number: '))
    c=a/b
    d=a*b
    e=a+b
    print(c)
    print(d)
    print(e)
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') # if NameEroor is not caught it will come to TypeError
except ValueError as ex3:
    print('Try to give an integer input')
except ZeroDivisionError:
    print('Dividing by zero cant be done, provide number greater than 0')# handling zero division error with custom message
except Exception as ex:
    print(ex)

Enter the first number: 12
Enter the second number: 0
Dividing by zero cant be done, provide number greater than 0


In [26]:
try:
    a=int(input('Enter the first number: '))
    b=int(input('Enter the second number: '))
    c=a/b
    d=a*b
    e=a+b
    
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') # if NameEroor is not caught it will come to TypeError
except ValueError as ex3:
    print('Try to give an integer input')
except ZeroDivisionError:
    print('Dividing by zero cant be done, provide number greater than 0')# handling zero division error with custom message
except Exception as ex:
    print(ex)
else: # we can aslo use else in try block, if error is caught this wont be executed
    print(c)
    print(d)
    print(e)

Enter the first number: 12
Enter the second number: 0
Dividing by zero cant be done, provide number greater than 0


In [28]:
try:
    a=int(input('Enter the first number: '))
    b=int(input('Enter the second number: '))
    c=a/b
    d=a*b
    e=a+b
    
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') # if NameEroor is not caught it will come to TypeError
except ValueError as ex3:
    print('Try to give an integer input')
except ZeroDivisionError:
    print('Dividing by zero cant be done, provide number greater than 0')# handling zero division error with custom message
except Exception as ex:
    print(ex)
else: # we can aslo use else in try block, if error is caught this wont be executed
    print(c)
    print(d)
    print(e)

Enter the first number: 12
Enter the second number: 6
2.0
72
18


In [29]:
# Try else finally

try:
    a=int(input('Enter the first number: '))
    b=int(input('Enter the second number: '))
    c=a/b
    d=a*b
    e=a+b
    
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') # if NameEroor is not caught it will come to TypeError
except ValueError as ex3:
    print('Try to give an integer input')
except ZeroDivisionError:
    print('Dividing by zero cant be done, provide number greater than 0')# handling zero division error with custom message
except Exception as ex:
    print(ex)
else: # we can aslo use else in try block
    print(c)
    print(d)
    print(e)
finally:
    print('The execution is done')# finally block will always get executed, even if except or else block isnt executed

Enter the first number: 12
Enter the second number: 0
Dividing by zero cant be done, provide number greater than 0
The execution is done


In [30]:
# Try else finally

try:
    a=int(input('Enter the first number: '))
    b=int(input('Enter the second number: '))
    c=a/b
    d=a*b
    e=a+b
    
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') # if NameEroor is not caught it will come to TypeError
except ValueError as ex3:
    print('Try to give an integer input')
except ZeroDivisionError:
    print('Dividing by zero cant be done, provide number greater than 0')# handling zero division error with custom message
except Exception as ex:
    print(ex)
else: # we can aslo use else in try block
    print(c)
    print(d)
    print(e)
finally:
    print('The execution is done')# finally block will always get executed, even if except or else block isnt executed

Enter the first number: 12
Enter the second number: 6
2.0
72
18
The execution is done


In [4]:
# Try to ask the user to input an integer and if they give an input other than a integer ask them again and again until 
# they give output as an integer

def askint():
    while True: # the while loop will run only if its a True
        try:
            a = int(input('Enter an integer: '))
            break
        except Exception as ex:
            print(ex)
            continue
        finally:
            print('Done')
    print(a)

In [5]:
askint()

Enter an integer: r
invalid literal for int() with base 10: 'r'
Done
Enter an integer: t
invalid literal for int() with base 10: 't'
Done
Enter an integer: y
invalid literal for int() with base 10: 'y'
Done
Enter an integer: 8
Done
8


In [6]:
try:
    a=int(input('Enter the first number: '))
    b=int(input('Enter the second number: '))
    c=a/b
    d=a*b
    e=a+b

#handling multiple error in one
except (NameError,TypeError,ValueError,ZeroDivisionError,Exception):
    print('There is an error')

Enter the first number: 6
Enter the second number: 0
There is an error


## Custom Exception

In [15]:
class Error(Exception):
    pass

class dobException(Error):
    pass

class specialageException(Error):
    pass

In [17]:
# If the age is between 18-35 do not raise an exception, if it is more than 35 or less than 18
# then raise your dobException, if age is equal to 36 raise specialageException

try:
    age=int(input('Enter your age : '))
    if age>=18 and age<=35:
        print('The age is valid to apply')
    elif age==36:
        raise specialageException
    else:
        raise dobException # we have raised custom exception condition here
        
except NameError as ex1:
    print('The user have not defined the variable')
except TypeError as ex2:
    print('Try to make the data type similar') 
except ValueError as ex3:
    print('Try to give an integer input')
except dobException as db: # we have used custom exception here
    print('The age is Not valid to apply')
except specialageException as sa: # we have used custom exception here
    print('This is a special age and you get benefits')
except Exception as ex:
    print(ex)

Enter your age : 36
This is a special age and you get benefits


## Assert Exception

Program execution proceeds only if the expression is true and raises the assertion error when it is false

In [20]:
try:
    num = int(input('Enter an even number: '))
    assert num%2==0
    print('The number is Even')
except AssertionError:
    print('You have not entered an even number')

Enter an even number: 3
You have not entered an even number


# Logging

Once we are done debugging, we will have to end up spending a lot of time removing print() calls from our code for each log message. We might even accidentally remove some print() calls that were being used for non-log messages. The nice thing about log messages is that we are free to fill our program with as many as we like, and we can always disable them later by adding a single logging.disable(logging.CRITICAL) call. Unlike print(), the logging module makes it easy to switch between showing and hiding log messages.Also Logging messages provide time stamps.

Log messages are intended for the programmer, not the user. The user won’t care about the contents of some dictionary value we need to see to help with debugging. 

In [1]:
import logging as lg

In [2]:
import os 

In [3]:
os.mkdir('logging')

In [3]:
os.chdir(os.getcwd()+'\\'+'logging')

In [5]:
pwd

'E:\\Full_Stack_data_science\\Python\\logging'

In [6]:
lg.basicConfig(filename = 'test.log',level = lg.INFO, format = '%(asctime)s %(message)s') 
#here it should be uppercase INFO
#format gives the date format
# level we have mentioned as INFO, we can also mention it as ERROR, that is useful when using Exception handling
# where we can use this ERROR type to catch exception

In [7]:
lg.info('This is the start of the program')#here it should be lowercase info

In [8]:
lg.warning('This is the first warning message you are recieving')

In [9]:
lg.error('This is an error message')

In [10]:
def test(a,b):
    try:
        lg.info('This is a start of function')
        lg.info('The two values are '+str(a)+' '+'and'+' '+str(b))# capture and log the 2 values
        div = a/b
        return div
    except Exception as e:
        print('Check the log for more info about this error')
        lg.error('Error has occured')
        lg.exception(str(e)) # this stores the error in log in string format

In [11]:
test(4,0) #log will have stored all info about this error

Check the log for more info about this error


In [12]:
lg.shutdown()

### test.log file

2021-04-12 12:47:44,970 This is the start of the program

2021-04-12 12:47:45,468 This is the first warning message you are recieving

2021-04-12 12:47:46,002 This is an error message

2021-04-12 12:47:47,687 This is a start of function

2021-04-12 12:47:47,688 The two values are 4 and 0

2021-04-12 12:47:47,689 Error has occured

2021-04-12 12:47:47,690 division by zero

Traceback (most recent call last):

  File "<ipython-input-10-884cabe42384>", line 5, in test
    
    div = a/b
    
ZeroDivisionError: division by zero


In [19]:
# Task
#1. Create a logger 
#2. Create a function that can take any number of input as argument and return sum of all those numbers
#3. Capture user input in log file
#4. Give the user information of the function
#5. Read a log file from python and print it on the console

In [1]:
import logging as lg

In [2]:
import os 

In [ ]:
os.mkdir('logging')

In [3]:
os.chdir(os.getcwd()+'\\'+'logging')

In [4]:
#1
lg.basicConfig(filename = 'test1.log',level = lg.INFO) 

In [5]:
#2
def add(*num):
    lg.info('This is the start of add function') #4
    lg.info('Provide series of numbers separated by comma to get sum of all those values')
    sum = 0
    for i in num:
        try:
            #3
            lg.info('The input value is: '+str(i))
            sum = i+sum
        except Exception as e:
            print('Check the log for more info about this error')
            lg.error('Error has occured')
            lg.exception(str(e))
    return sum

In [6]:
add(2,3,4,5,6)

20

In [7]:
#2
def inf_add():
    lg.info('This is the start of inf_add function') #4
    lg.info('Give numbers to get sum of all those numbers and to quit press q')
    j = True
    sum = 0
    while j==True:
        a = input('Enter a number to add or q to quit: ')
        if a == 'q':
            break
        else:
            try:
                b = int(a)
                #3
                lg.info('The value is : '+str(b))
                sum = b + sum
            except Exception as e:
                print('Check the log for more info about this error')
                lg.error('Error has occured')
                lg.exception(str(e))
    return sum

In [8]:
inf_add()

Enter a number to add or q to quit: 6
Enter a number to add or q to quit: 7
Enter a number to add or q to quit: 8
Enter a number to add or q to quit: 9
Enter a number to add or q to quit: q


30

In [9]:
filepath = input('Provide the path of the log file to be read: ')
#E:\\Full_Stack_data_science\\Python\\logging\\test1.log
f = open(filepath,mode='r') #5
print(f.read())
f.close()

Provide the path of the log file to be read: E:\\Full_Stack_data_science\\Python\\logging\\test1.log
INFO:root:This is the start of add function
INFO:root:Provide series of numbers separated by comma to get sum of all those values
INFO:root:The input value is: 2
INFO:root:The input value is: 3
INFO:root:The input value is: 4
INFO:root:The input value is: 5
INFO:root:The input value is: 6
INFO:root:This is the start of inf_add function
INFO:root:Give numbers to get sum of all those numbers and to quit press q
INFO:root:The value is : 6
INFO:root:The value is : 7
INFO:root:The value is : 8
INFO:root:The value is : 9



### test1.log file

INFO:root:This is the start of add function

INFO:root:Provide series of numbers separated by comma to get sum of all those values

INFO:root:The input value is: 2

INFO:root:The input value is: 3

INFO:root:The input value is: 4

INFO:root:The input value is: 5

INFO:root:The input value is: 6

INFO:root:This is the start of inf_add function

INFO:root:Give numbers to get sum of all those numbers and to quit press q

INFO:root:The value is : 6

INFO:root:The value is : 7

INFO:root:The value is : 8

INFO:root:The value is : 9

## Stream Handler and Add Handler

In [1]:
import os 
os.chdir('E:\\Full_Stack_data_science\\Python\\logging')

In [2]:
pwd

'E:\\Full_Stack_data_science\\Python\\logging'

In [3]:
import logging

In [4]:
# When we are trying to access log from multiple user, we can create multiple logger instances, 
#by doing this we can find out which user has logged what information

# here we are also streaming the logging info into console using StreamHandler, instead of opening log file
# and reading it and then printing it in the console as we did in earlier task

# This is using level = logging.INFO, it shows only the info even when logger2.debug is mentioned

logging.basicConfig(filename = 'app1.log',level = logging.INFO,format = "%(asctime)s %(name)s %(levelname)s %(message)s")
console_log = logging.StreamHandler()# this will stream info onto the console showing what is being logged
console_log.setLevel(logging.INFO) # here since we havent used addHandler we get name as root

format = logging.Formatter('%(asctime)s %(name)s %(levelname)s %(message)s')
console_log.setFormatter(format)
logging.getLogger().addHandler(console_log) #instead root name we get any name we specify
logging.info('This is the starting')

logger1 = logging.getLogger('user1') # instead of root name we get user1
logger2 = logging.getLogger('user2')# instead of root name we get user2
# so we will know the log information of particular logger who logged it, it wont just say root

logger1.info('This is the info about logger1')
logger2.debug('This is debug for logger2') # this wont be logged as level is not logging.DEBUG instead it is logging.INFO
logger2.info('This is the info about logger2')

2021-04-13 12:49:52,644 root INFO This is the starting
2021-04-13 12:49:52,649 user1 INFO This is the info about logger1
2021-04-13 12:49:52,650 user2 INFO This is the info about logger2


### app1.log file

2021-04-13 12:49:52,644 root INFO This is the starting

2021-04-13 12:49:52,649 user1 INFO This is the info about logger1

2021-04-13 12:49:52,650 user2 INFO This is the info about logger2

In [4]:
#This is using level = logging.DEBUG, it shows DEBUG also along with INFO

logging.basicConfig(filename = 'app2.log',level = logging.DEBUG,format = "%(asctime)s %(name)s %(levelname)s %(message)s")
console_log = logging.StreamHandler() # this will stream info onto the console showing what is being logged
            
console_log.setLevel(logging.DEBUG) # here since we havent used addHandler we get name as root

format = logging.Formatter('%(asctime)s %(name)s %(levelname)s %(message)s')
console_log.setFormatter(format)
logging.getLogger().addHandler(console_log) #instead root name we get any name we specify
logging.info('This is the starting')

logger1 = logging.getLogger('user1') # instead of root name we get user1
logger2 = logging.getLogger('user2')# instead of root name we get user2
# so we will know the log information of particular logger who logged it, it wont just say root

logger1.info('This is the info about logger1')
logger1.error('This is error')
logger2.debug('This is debug for logger2')
logger2.info('This is the info about logger2')

2021-04-13 12:51:37,596 root INFO This is the starting
2021-04-13 12:51:37,601 user1 INFO This is the info about logger1
2021-04-13 12:51:37,603 user1 ERROR This is error
2021-04-13 12:51:37,605 user2 DEBUG This is debug for logger2
2021-04-13 12:51:37,606 user2 INFO This is the info about logger2


### app2.log file

2021-04-13 12:51:37,596 root INFO This is the starting

2021-04-13 12:51:37,601 user1 INFO This is the info about logger1

2021-04-13 12:51:37,603 user1 ERROR This is error

2021-04-13 12:51:37,605 user2 DEBUG This is debug for logger2

2021-04-13 12:51:37,606 user2 INFO This is the info about logger2

# Debugging

In [1]:
!pip install ipdb

Processing c:\users\shashank\appdata\local\pip\cache\wheels\70\56\a8\68a89798bb8783aa4a9d5bd5b7cd3a03a53aca225f6f34ba99\ipdb-0.13.7-py3-none-any.whl
  Using cached ipython-7.22.0-py3-none-any.whl (785 kB)
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Attempting uninstall: ipython
    Found existing installation: ipython 7.12.0
    Uninstalling ipython-7.12.0:
      Successfully uninstalled ipython-7.12.0


In [3]:
import ipdb

In [4]:
def testdebug():
    ipdb.set_trace() # start tracing code from this point
    l = []
    for i in range(10):
        for k in range(5):
            l.append(k)
            if i==4:
                print('this is 4')
            print('We have appeneded the data')
    return l

In [ ]:
testdebug() #when prompted press 'h' to show help and all keys and topics

> <ipython-input-11-bba43b587708>(3)testdebug()
      2     ipdb.set_trace() # start tracing code
----> 3     l = []
      4     for i in range(10):

ipdb> n
> <ipython-input-11-bba43b587708>(4)testdebug()
      3     l = []
----> 4     for i in range(10):
      5         for k in range(5):

ipdb> n
> <ipython-input-11-bba43b587708>(5)testdebug()
      4     for i in range(10):
----> 5         for k in range(5):
      6             l.append(k)

ipdb> n
> <ipython-input-11-bba43b587708>(6)testdebug()
      5         for k in range(5):
----> 6             l.append(k)
      7             if i==4:

ipdb> n
> <ipython-input-11-bba43b587708>(7)testdebug()
      6             l.append(k)
----> 7             if i==4:
      8                 print('this is 4')

ipdb> n
> <ipython-input-11-bba43b587708>(9)testdebug()
      8                 print('this is 4')
----> 9             print('We have appeneded the data')
     10     return l

ipdb> n
We have appeneded the data
> <ipython-input-11-bba43

In [8]:
testdebug() # by assigning k=4 we no need to pass through all that loop, instead we can go directly to i=4


> <ipython-input-4-bba43b587708>(3)testdebug()
      2     ipdb.set_trace() # start tracing code
----> 3     l = []
      4     for i in range(10):

ipdb> n
> <ipython-input-4-bba43b587708>(4)testdebug()
      3     l = []
----> 4     for i in range(10):
      5         for k in range(5):

ipdb> n
> <ipython-input-4-bba43b587708>(5)testdebug()
      4     for i in range(10):
----> 5         for k in range(5):
      6             l.append(k)

ipdb> i
0
ipdb> i=4
ipdb> i
4
ipdb> n
> <ipython-input-4-bba43b587708>(6)testdebug()
      5         for k in range(5):
----> 6             l.append(k)
      7             if i==4:

ipdb> n
> <ipython-input-4-bba43b587708>(7)testdebug()
      6             l.append(k)
----> 7             if i==4:
      8                 print('this is 4')

ipdb> n
> <ipython-input-4-bba43b587708>(8)testdebug()
      7             if i==4:
----> 8                 print('this is 4')
      9             print('We have appeneded the data')

ipdb> n
this is 4
> <ipython

BdbQuit: 